formula ::= exp
exp ::= exp '=' exp
exp ::= exp '<=' exp
exp ::= exp '>=' exp
exp ::= exp '<>' exp
exp ::= exp '>' exp
exp ::= exp '<' exp
exp ::= exp '&' exp
exp ::= exp '+' exp
exp ::= exp '-' exp
exp ::= exp '*' exp
exp ::= exp '/' exp
exp ::= exp '^' exp
exp ::= '+' exp
exp ::= '-' exp
exp ::= '@' exp
exp ::= exp '%'
exp ::= '(' exp ')'
exp ::= 'NUMBER'
exp ::= 'STRING'
exp ::= 'LOGIC'
exp ::= 'ERROR'
exp ::= reference
referenceItem ::= 'CELL'
referenceItem ::= 'NAME'
referenceItem ::= structureReference
reference ::= reference 'REF_UNION_OPERATOR' reference
reference ::= reference reference
reference ::= reference 'REF_RANGE_OPERATOR' reference
reference ::= referenceItem
exp ::= functionExp
exp ::= array
arrayElement ::= 'STRING'
arrayElement ::= 'NUMBER'
arrayElement ::= 'LOGIC'
arrayElement ::= 'ERROR'
array ::= '{' arrayElement ( 'ARRAY_SEPARATOR' arrayElement )* '}'
functionExp ::= 'FUNCTION' '(' argumentsList ')'
argumentsList ::= exp? ( 'ARGUMENT_SEPARATOR' exp? )*
structureReference ::= 'TABLE_NAME' tableSpecifier
structureReference ::= tableSpecifier
tableSpecifier ::= 'TABLE_ITEM_SPECIFIER'
tableSpecifier ::= '[' tableSpecifierInner ']'
tableThisRow ::= 'TABLE_AT'
tableThisRow ::= 'TABLE_AT' 'TABLE_COLUMN_SPECIFIER'
tableSpecifierInner ::= tableThisRow
tableSpecifierInner ::= tableColumnSpecifier
tableSpecifierItem ::= 'TABLE_COLUMN_SPECIFIER'
tableSpecifierItem ::= 'TABLE_ITEM_SPECIFIER'
tableColumnSpecifier ::= tableSpecifierItem ( 'SPECIFIER_SEPARATOR' tableSpecifierItem )*