Exp ::= primaryExpression
Exp ::= Exp '^' Exp
Exp ::= Exp '-' Exp
Exp ::= Exp '*' Exp
Exp ::= Exp '/' Exp
Exp ::= '-' Exp
Exp ::= Exp '+' Exp
primaryExpression ::= '(' Exp ')'
primaryExpression ::= 'NUMBER'