exp ::= primaryExpression 
exp ::= exp  '^'  exp 
exp ::= exp  '-'  exp 
exp ::= exp  '*'  exp 
exp ::= exp  '/'  exp 
exp ::= '-'  exp 
exp ::= exp  '+'  exp 
primaryExpression ::= '('  exp  ')' 
primaryExpression ::= 'NUMBER' 