/*
Generated By kison v0.5.3

Generate time: Mon Oct 11 2021 20:27:21 GMT+0800 (中国标准时间)
*/
var $parser = (function (undefined) {
  var AstNode = class AstNode {
    parent = null;
    symbol = "";
    label = "";
    type = "";

    constructor(cfg) {
      Object.assign(this, cfg);
      if (cfg.children) {
        this.setChildren(cfg.children);
      }
    }

    addChild(c) {
      this.addChildren([c]);
    }

    addChildren(cs) {
      this.children.push(...cs);
      this.setChildren(this.children);
    }

    setChildren(cs) {
      if (!cs.length) {
        this.children = [];
        return;
      }
      const first = cs[0];
      const last = cs[cs.length - 1];
      this.start = first.start;
      this.end = last.end;
      this.firstLine = first.firstLine;
      this.lastLine = last.lastLine;
      this.firstColumn = first.firstColumn;
      this.lastColumn = last.lastColumn;
      this.children = cs;
      for (const c of cs) {
        c.parent = this;
      }
    }

    toJSON() {
      const ret = {};
      for (const k of Object.keys(this)) {
        if (k !== "parent" && k !== "t") {
          ret[k] = this[k];
        }
      }
      return ret;
    }
  };
  var filterRhs = function (rhs) {
    return rhs.filter((r) => typeof r === "string");
  };
  var getParseError = function (getExpected) {
    const expected = getExpected();
    const tips = [];
    if (expected.length) {
      tips.push("'" + expected.join("', '") + "' expected.");
    }
    tips.push("current token: '" + lexer.getCurrentToken().token + "'.");
    const tip = tips.join("\n");
    return {
      errorMessage: [
        "syntax error at line " +
          lexer.lineNumber +
          ":\n" +
          lexer.showDebugInfo(),
        ...tips,
      ].join("\n"),
      tip,
    };
  };
  var cleanAst = function (ast, transformNode) {
    if (!transformNode) {
      return ast;
    }
    if (ast.children) {
      let children;
      let childrenChanged;
      while (true) {
        let changed = false;
        let index = 0;
        children = [];
        for (const c of ast.children) {
          const node = transformNode({
            node: c,
            index,
            parent: ast,
            defaultTransformNode: defaultTransformAstNode,
          });
          if (Array.isArray(node)) {
            children.push(...node);
          } else if (node) {
            children.push(node);
          }
          changed = changed || node !== c;
          index++;
        }
        if (!changed) {
          break;
        } else {
          ast.setChildren(children);
          childrenChanged = true;
        }
      }
      if (childrenChanged && ast.parent) {
        cleanAst(ast.parent, transformNode);
      } else {
        for (const c of children) {
          cleanAst(c, transformNode);
        }
      }
    }
    return ast;
  };
  var getAstRootNode = function (astStack, transformNode, raw) {
    let ast = astStack[0];
    ast = ast?.children?.[0];
    ast = ast?.children?.[0];
    if (ast) {
      ast.parent = null;
    }
    if (raw) {
      return ast;
    }
    return ast && cleanAst(ast, transformNode);
  };
  var checkProductionLabelIsSame = function (node, parent) {
    if (node.label || parent.label) {
      if (node.label === parent.label) {
        return node.children;
      }
      return node;
    }
    return node.children;
  };
  var defaultTransformAstNode = function ({ node, parent }) {
    if (node.token || node.error || node.symbol !== parent.symbol) {
      return node;
    }
    if (parent.children.length === 1) {
      // do not check label
      // replace label!
      parent.label = node.label;
      return node.children;
    }
    if (node.children.length > 1) {
      return node;
    }
    // drill down to token
    if (node.children[0]?.token) {
      // do not check label
      // parent.label = node.label;
      return node.children;
    }
    return checkProductionLabelIsSame(node, parent);
  };
  var isAddAstNodeFlag = function (t) {
    return t === productionAddAstNodeFlag;
  };
  var isProductionEndFlag = function (t) {
    return t === productionEndFlag;
  };
  var isOneOrMoreSymbol = function (s) {
    return typeof s === "string" && s.length > 1 && s.endsWith("+");
  };
  var isOptionalSymbol = function (s) {
    return typeof s === "string" && s.length > 1 && s.endsWith("?");
  };
  var normalizeSymbol = function (s) {
    return isOptionalSymbol(s) || isZeroOrMoreSymbol(s) || isOneOrMoreSymbol(s)
      ? s.slice(0, -1)
      : s;
  };
  var isZeroOrMoreSymbol = function (s) {
    return typeof s === "string" && s.length > 1 && s.endsWith("*");
  };
  var productionSkipAstNodeSet = undefined;
  var symbolStack = [{}];
  var productionsBySymbol = {};
  var cachedStateMatchMap = undefined;
  var productionAddAstNodeFlag = 1;
  var productionEndFlag = 2;
  function mix(to, from) {
    for (var f in from) {
      to[f] = from[f];
    }
  }
  function isArray(obj) {
    return "[object Array]" === Object.prototype.toString.call(obj);
  }
  function each(object, fn, context) {
    if (object) {
      var key,
        val,
        length,
        i = 0;

      context = context || null;

      if (!isArray(object)) {
        for (key in object) {
          // can not use hasOwnProperty
          if (fn.call(context, object[key], key, object) === false) {
            break;
          }
        }
      } else {
        length = object.length;
        for (val = object[0]; i < length; val = object[++i]) {
          if (fn.call(context, val, i, object) === false) {
            break;
          }
        }
      }
    }
  }
  function inArray(item, arr) {
    for (var i = 0, l = arr.length; i < l; i++) {
      if (arr[i] === item) {
        return true;
      }
    }
    return false;
  }
  var Lexer = function (cfg) {
    this.nextTokens = [];
    if (Lexer.supportSticky === undefined) {
      try {
        Lexer.supportSticky = typeof /(?:)/.sticky == "boolean";
      } catch (e) {
        Lexer.supportSticky = false;
      }
    }

    const ruleIndexMap = (this.ruleIndexMap = {
      token: 0,
      regexp: 1,
      action: 2,
      filter: 3,
      state: 4,
    });
    const STATIC = Lexer.STATIC;
    this.tokenSet = new Set([
      STATIC.EOF_TOKEN,
      STATIC.UNKNOWN_TOKEN,
      STATIC.HIDDEN_TOKEN,
    ]);
    this.rules = [];
    this.defaultEnv = undefined;
    mix(this, cfg);
    this.rules = this.rules.concat();

    this.regexpIndex = this.isCompress ? this.ruleIndexMap.regexp : "regexp";
    this.getRuleItem = this.isCompress
      ? this.getRuleItemCompress
      : this.getRuleItemNoCompress;

    this.transformRules();
    this.userData = {};
    const errorRule = (this.errorRule = {
      regexp: this.matchAny,
      token: Lexer.STATIC.UNKNOWN_TOKEN,
    });
    for (const rule of this.rules) {
      const token = this.getRuleItem(rule, "token");
      if (token) {
        this.tokenSet.add(token);
      }
    }
    if (this.isCompress) {
      const errorRuleCompress = (this.errorRule = []);
      errorRuleCompress[ruleIndexMap.token] = errorRule.token;
      errorRuleCompress[ruleIndexMap.regexp] = errorRule.regexp;
    }
    this.resetInput(this.input);
    this.options = {};
  };
  Lexer.prototype = {
    transformRegExp: function (obj, p, disableSticky) {
      const pattern = obj[p];
      if (pattern.test) {
        let source = pattern.source;
        if (source.startsWith("^")) {
          source = source.slice(1);
        }
        var flags = Lexer.supportSticky && !disableSticky ? "gy" : "g";
        if (pattern.multiline) flags += "m";
        if (pattern.ignoreCase) flags += "i";
        if (pattern.unicode) flags += "u";
        obj[p] = new RegExp(source, flags);
      } else if (typeof pattern === "object") {
        for (const k of Object.keys(pattern)) {
          this.transformRegExp(pattern, k);
        }
      }
    },
    hasToken: function (t) {
      return this.tokenSet.has(t);
    },
    transformRules: function () {
      if (Lexer.supportSticky) {
        const { regexpIndex } = this;
        for (const r of this.rules) {
          this.transformRegExp(r, regexpIndex);
        }
      }
    },
    matchAny: function () {
      return this.end < this.input.length ? this.input.charAt(this.end) : false;
    },
    addRule: function (rule) {
      this.rules.push(rule);
      const token = this.getRuleItem(rule, "token");
      if (token) {
        this.tokenSet.add(token);
      }
    },
    resetInput: function (input) {
      this.token = undefined;
      this.tokensQueue = [];
      this.nextTokens = [];
      this.tokens = [];
      this.userData = {};
      this.input = input;
      this.matched = "";
      this.stateStack = [Lexer.STATIC.INITIAL_STATE];
      this.match = "";
      this.text = "";
      this.firstLine = 1;
      this.lineNumber = 1;
      this.lastLine = 1;
      this.start = 0;
      this.end = 0;
      this.firstColumn = 1;
      this.lastColumn = 1;
    },
    getRuleItemNoCompress: function (rule, itemType) {
      return rule[itemType];
    },
    getRuleItemCompress: function (rule, itemType) {
      return rule[this.ruleIndexMap[itemType]];
    },
    getCurrentRules: function () {
      var currentState = this.stateStack[this.stateStack.length - 1],
        rules = [];
      each(this.rules, (r) => {
        var filter = this.getRuleItem(r, "filter");
        if (filter) {
          if (filter.call(this)) {
            rules.push(r);
          }
          return;
        }
        var state = this.getRuleItem(r, "state");
        if (!state) {
          if (currentState === Lexer.STATIC.INITIAL_STATE) {
            rules.push(r);
          }
        } else if (inArray(currentState, state)) {
          rules.push(r);
        }
      });
      rules.push(this.errorRule);
      return rules;
    },
    peekState: function (n) {
      n = n || 1;
      return this.mapReverseState(this.stateStack[this.stateStack.length - n]);
    },
    pushState: function (state) {
      this.stateStack.push(this.mapState(state));
    },
    popState: function (num) {
      num = num || 1;
      var ret;
      while (num--) {
        ret = this.stateStack.pop();
      }
      return ret && this.mapReverseState(ret);
    },
    showDebugInfo: function () {
      var { DEBUG_CONTEXT_LIMIT } = Lexer.STATIC;
      var { matched, match, input } = this;

      matched = matched.slice(0, matched.length - match.length);
      var past =
          (matched.length > DEBUG_CONTEXT_LIMIT ? "..." : "") +
          matched
            .slice(0 - DEBUG_CONTEXT_LIMIT)
            .split("\n")
            .join(" "),
        next = match + input.slice(this.end);
      //#JSCOVERAGE_ENDIF
      next =
        next.slice(0, DEBUG_CONTEXT_LIMIT).split("\n").join(" ") +
        (next.length > DEBUG_CONTEXT_LIMIT ? "..." : "");
      return past + next + "\n" + new Array(past.length + 1).join("-") + "^";
    },
    mapSymbol: function (n) {
      return n;
    },
    mapReverseSymbol: function (n) {
      return n;
    },
    mapState: function (n) {
      return n;
    },
    mapReverseState: function (n) {
      return n;
    },
    toJSON: function () {
      const currentToken = this.getCurrentToken();
      return {
        text: currentToken.text,
        firstLine: currentToken.firstLine,
        firstColumn: currentToken.firstColumn,
        lastLine: currentToken.lastLine,
        lastColumn: currentToken.lastColumn,
        token: currentToken.token,
        start: currentToken.start,
        end: currentToken.end,
      };
    },
    stash: function () {
      this.stashIndex = this.tokens.length;
    },
    stashPop: function () {
      this.nextTokens = [
        ...this.tokens.slice(this.stashIndex),
        ...this.nextTokens,
      ];
      this.tokens.length = this.stashIndex;
    },
    matchRegExp: function (regexp) {
      if (regexp.test) {
        regexp.lastIndex = this.end;
        const ret = regexp.exec(this.input);
        if (ret && ret.index !== this.end) {
          return null;
        }
        return ret;
      }
      return regexp.call(this, this);
    },
    pushToken: function (token) {
      const tokens = this.tokens;
      if (tokens[tokens.length - 1]?.token === Lexer.STATIC.EOF_TOKEN) {
        tokens.pop();
      }
      tokens.push(token);
    },
    lex: function () {
      const { EOF_TOKEN, HIDDEN_TOKEN } = Lexer.STATIC;

      const token = this.nextToken();
      const tokens = this.tokens;
      const lastToken = tokens[tokens.length - 1];
      if (
        lastToken &&
        token.token === EOF_TOKEN &&
        lastToken.token === EOF_TOKEN
      ) {
        return token;
      }
      this.tokens.push(token);
      if (token.token === HIDDEN_TOKEN || !token.token) {
        return this.lex();
      }
      return token;
    },
    getCurrentToken: function () {
      if (this.tokens[this.tokens.length - 1]) {
        return this.tokens[this.tokens.length - 1];
      }
      return this.lex();
    },
    getLastToken: function () {
      return this.tokens[this.tokens.length - 2] || this.getCurrentToken();
    },
    nextChar: function (index = 0) {
      return this.getChar(this.end + index);
    },
    nextCharCode: function (index = 0) {
      return this.getCharCode(this.end + index);
    },
    nextStartsWith: function (search) {
      let { input, end } = this;
      const l = search.length;
      for (let i = 0; i < l; i++) {
        if (input.charAt(end++) !== search.charAt(i)) {
          return false;
        }
      }
      return true;
    },
    nextCharAt: function (index) {
      return this.input.charAt(this.end + index);
    },
    nextLength: function () {
      return this.input.length - this.end;
    },
    getChar: function (index = 0) {
      if (this.options.unicode) {
        const code = this.input.codePointAt(index);
        if (code === undefined || isNaN(code)) {
          return "";
        }
        return String.fromCodePoint(code);
      }
      return this.input.charAt(index);
    },
    getCharCode: function (index = 0) {
      if (this.options.unicode) {
        return this.input.codePointAt(index);
      }
      return this.input.charCodeAt(index);
    },
    getTokensLength: function () {
      return this.tokens.length;
    },
    nextToken: function () {
      if (this.nextTokens.length) {
        return this.nextTokens.shift();
      }
      var i,
        rule,
        m,
        ret,
        lines,
        rules = this.getCurrentRules();

      var { input } = this;

      var { env = this.defaultEnv } = this.options;

      this.match = this.text = "";

      if (this.end >= input.length) {
        this.token = Lexer.STATIC.EOF_TOKEN;
        this.start = this.end;
        this.firstLine = this.lastLine;
        this.firstColumn = this.lastColumn;
        return {
          text: "",
          t: this.mapSymbol(this.token),
          token: this.token,
          start: this.start,
          end: this.end,
          firstLine: this.firstLine,
          firstColumn: this.firstColumn,
          lastLine: this.lastLine,
          lastColumn: this.lastColumn,
        };
      }

      for (i = 0; i < rules.length; i++) {
        rule = rules[i];
        var regexp = this.getRuleItem(rule, "regexp"),
          token = this.getRuleItem(rule, "token"),
          action = this.getRuleItem(rule, "action");

        if (
          typeof regexp !== "function" &&
          regexp &&
          env &&
          typeof regexp.test !== "function"
        ) {
          regexp = regexp[env];
        }

        if (!regexp) {
          continue;
        }

        //#JSCOVERAGE_ENDIF
        if ((m = this.matchRegExp(regexp))) {
          this.start = this.end;
          this.end += m[0].length;
          lines = m[0].split("\n");
          lines.shift();
          this.lineNumber += lines.length;
          const position = {
            start: this.start,
            end: this.end,
            firstLine: this.lastLine,
            lastLine: this.lineNumber,
            firstColumn: this.lastColumn,
            lastColumn: lines.length
              ? lines[lines.length - 1].length + 1
              : this.lastColumn + m[0].length,
          };

          mix(this, position);

          var match;
          // for error report
          match = this.match = m[0];

          // all matches
          this.matches = m;
          // may change by user
          this.text = match;
          // matched content utils now
          this.matched += match;
          ret = action && action.call(this);

          if (ret === undefined) {
            ret = token;
          } else {
            ret = this.mapSymbol(ret);
          }

          if (ret) {
            this.token = this.mapReverseSymbol(ret);
            return {
              text: this.text,
              token: this.token,
              t: ret,
              ...position,
            };
          } else {
            // ignore
            return this.nextToken();
          }
        }
      }
    },
  };
  Lexer.STATIC = {
    INITIAL_STATE: "I",
    DEBUG_CONTEXT_LIMIT: 20,
    EOF_TOKEN: "$EOF",
    UNKNOWN_TOKEN: "$UNKNOWN",
    HIDDEN_TOKEN: "$HIDDEN",
  };
  var lexer = new Lexer({
    rules: [
      ["NEW_LINE", /\n/g],
      ["$HIDDEN", /\s+/g],
      ["NUMBER", /[0-9]+(\.[0-9]+)?\b/g],
      ["statement+", /statement\+/g],
      ["+", /\+/g],
      ["-", /\-/g],
      ["*", /\*/g],
      ["/", /\//g],
      ["^", /\^/g],
      ["(", /\(/g],
      [")", /\)/g],
    ],
    isCompress: 1,
    defaultEnv: undefined,
  });
  function lex(input, options = {}) {
    lexer.options = options;
    lexer.resetInput(input);
    const { state } = options;
    if (state) {
      if (state.userData) {
        lexer.userData = state.userData;
      }
      if (state.stateStack) {
        lexer.stateStack = state.stateStack;
      }
    }
    while (lexer.lex().token !== Lexer.STATIC.EOF_TOKEN);
    return {
      state: {
        userData: lexer.userData,
        stateStack: lexer.stateStack,
      },
      tokens: lexer.tokens,
    };
  }
  var parser = {
    productions: [
      ["$START", ["program"]],
      ["program", ["statements"]],
      ["statements", ["statement", "statement*"]],
      ["statement", ["exp", "NEW_LINE"]],
      ["exp_p_end", ["NUMBER"]],
      ["exp_p_end", ["(", "exp", ")"]],
      ["(exp)1_", ["+", "exp_p_2", 1, "(exp)1_"]],
      ["exp", ["exp_p_2", 1, "(exp)1_"], undefined, "binary-exp"],
      ["(exp)1_", ["-", "exp_p_2", 1, "(exp)1_"]],
      ["(exp_p_2)1_", ["*", "exp_p_3", 1, "(exp_p_2)1_"]],
      ["exp_p_2", ["exp_p_3", 1, "(exp_p_2)1_"], undefined, "binary-exp"],
      ["(exp_p_2)1_", ["/", "exp_p_3", 1, "(exp_p_2)1_"]],
      ["exp_p_3", ["exp_p_4"]],
      ["exp_p_3", ["exp_p_4", "^", "exp_p_3"], undefined, "binary-exp"],
      ["exp_p_4", ["exp_p_end"]],
      ["exp_p_4", ["-", "exp_p_4"]],
      ["(exp)1_", []],
      ["(exp_p_2)1_", []],
    ],
    productionIndexMap: {
      symbol: 0,
      rhs: 1,
      action: 2,
      label: 3,
    },
    getProductionItemByType: function (p, itemType) {
      if (this.isCompress) {
        return p[this.productionIndexMap[itemType]];
      }
      return p[itemType];
    },
    getProductionSymbol: function (p) {
      return this.getProductionItemByType(p, "symbol");
    },
    getProductionRhs: function (p) {
      return this.getProductionItemByType(p, "rhs");
    },
    getProductionAction: function (p) {
      return this.getProductionItemByType(p, "action");
    },
    getProductionLabel: function (p) {
      return this.getProductionItemByType(p, "label");
    },
    isCompress: 1,
  };
  parser.getProductionSymbol = parser.getProductionSymbol.bind(parser);
  parser.getProductionRhs = parser.getProductionRhs.bind(parser);
  parser.getProductionAction = parser.getProductionAction.bind(parser);
  parser.getProductionLabel = parser.getProductionLabel.bind(parser);
  parser.lexer = lexer;
  parser.lex = lex;
  parser.prioritySymbolMap = {
    exp_p_end: "exp",
    exp_p_1: "exp",
    exp_p_2: "exp",
    exp_p_3: "exp",
    exp_p_4: "exp",
  };
  productionSkipAstNodeSet = new Set([3, 6, 8, 9, 11, 16, 17]);
  var parse = function (input, options) {
    clearStateMatchCache();

    let recoveryTokens = [];
    const terminalNodes = [];

    function isExtraSymbol(ast) {
      return ast.children && !ast.children.length;
    }

    function peekStack(stack, n = 1) {
      return stack[stack.length - n];
    }

    function getOriginalSymbol(s) {
      let uncompressed = lexer.mapReverseSymbol(s);
      return prioritySymbolMap[uncompressed] || uncompressed;
    }

    options = options || {};
    let error;
    var {
      onErrorRecovery,
      onAction,
      lexerOptions = {},
      transformNode,
    } = options;

    if (transformNode !== false && !transformNode) {
      transformNode = defaultTransformAstNode;
    }

    var {
      lexer,
      productions,
      prioritySymbolMap,
      getProductionSymbol,
      getProductionRhs,
      getProductionLabel,
    } = parser;

    lexer.options = lexerOptions;
    const startSymbol = getProductionSymbol(productions[0]);
    symbolStack = [startSymbol];
    const astStack = [
      new AstNode({
        children: [],
      }),
    ];
    lexer.resetInput(input);
    let token;
    let next = null;

    let topSymbol;

    let errorNode;

    function peekSymbolStack(n = 1) {
      let index = symbolStack.length - n;
      while (
        index !== -1 &&
        symbolStack[index] &&
        symbolStack[index].type === "rule"
      ) {
        index--;
      }
      return symbolStack[index];
    }

    function popSymbolStack() {
      while (true) {
        const t = symbolStack.pop();
        if (!t || t.type !== "rule") {
          break;
        }
      }
      while (symbolStack[symbolStack.length - 1]?.type === "rule") {
        symbolStack.pop();
      }
    }

    let getExpected = function () {
      const s = topSymbol;
      if (!isSymbol(s)) {
        return [lexer.mapReverseSymbol(s)];
      }
      // get expected tokens from state machine
      return findExpectedTokenFromStateMachine(findSymbolIndex()).map((s) =>
        lexer.mapReverseSymbol(s)
      );
    };

    function closeAstWhenError() {
      errorNode = new AstNode({
        type: "token",
        error,
        ...error.lexer,
      });
      peekStack(astStack).addChild(errorNode);
      while (astStack.length !== 1) {
        const ast = astStack.pop();
        if (ast.symbol && isExtraSymbol(ast)) {
          const topAst = peekStack(astStack);
          topAst.children.pop();
          topAst.addChildren(ast.children);
        }
      }
    }

    function makeRuleIndexFlag(ruleIndex, ruleUnit) {
      return {
        type: "rule",
        ruleUnit,
        tokensLength: lexer.getTokensLength(),
        ruleIndex,
      };
    }

    function findSymbolIndex() {
      if (topSymbol === startSymbol) {
        return { childReverseIndex: -1, ruleIndex: -1 };
      }
      let i = -1;
      let top = symbolStack.length - 1;
      let ruleIndex = 0;
      while (symbolStack[top] !== topSymbol) {
        top--;
      }
      while (
        top !== -1 &&
        symbolStack[top] &&
        symbolStack[top].type !== "rule"
      ) {
        if (typeof symbolStack[top] === "string") {
          i++;
        }
        top--;
      }
      if (symbolStack[top]?.type === "rule") {
        ruleIndex = symbolStack[top].ruleIndex;
      }

      return { childReverseIndex: i, ruleIndex };
    }

    let production;

    const { EOF_TOKEN } = Lexer.STATIC;

    function pushRecoveryTokens(token) {
      let eof;
      if (recoveryTokens[recoveryTokens.length - 1]?.token === EOF_TOKEN) {
        eof = recoveryTokens.pop();
      }
      recoveryTokens.push(token);
      if (eof && token.token !== EOF_TOKEN) {
        recoveryTokens.push(eof);
      }
    }

    while (1) {
      topSymbol = peekSymbolStack();

      if (!topSymbol) {
        break;
      }

      while (isProductionEndFlag(topSymbol) || isAddAstNodeFlag(topSymbol)) {
        let ast = astStack.pop();
        if (isAddAstNodeFlag(topSymbol)) {
          const stackTop = peekStack(astStack);
          const wrap = new AstNode({
            type: "symbol",
            symbol: ast.symbol,
            children: [ast],
            label: ast.label,
          });
          stackTop.children.pop();
          stackTop.addChild(wrap);
          astStack.push(wrap);
        }
        popSymbolStack();
        topSymbol = peekSymbolStack();
        if (!topSymbol) {
          break;
        }
      }

      if (typeof topSymbol === "string") {
        if (!token) {
          token = lexer.lex();
          pushRecoveryTokens(token);
        }
        if (topSymbol === token.t) {
          popSymbolStack();
          const terminalNode = new AstNode(token);
          terminalNode.type = "token";
          terminalNodes.push(terminalNode);
          const parent = peekStack(astStack);
          parent.addChild(terminalNode);
          token = lexer.lex();
          pushRecoveryTokens(token);
          continue;
        }
        next = predictProductionIndexLLK(findSymbolIndex());
        if (next) {
          if (!isZeroOrMoreSymbol(topSymbol)) {
            popSymbolStack();
          }

          const { ruleIndex, unit } = next;

          production = productions[ruleIndex];

          if (productionSkipAstNodeSet?.has(ruleIndex)) {
            symbolStack.push.apply(
              symbolStack,
              getProductionRhs(production)
                .concat(makeRuleIndexFlag(ruleIndex, unit))
                .reverse()
            );
          } else {
            const newAst = new AstNode({
              type: "symbol",
              symbol: getOriginalSymbol(normalizeSymbol(topSymbol)),
              label: getOriginalSymbol(getProductionLabel(production)),
              children: [],
            });
            peekStack(astStack).addChild(newAst);
            astStack.push(newAst);
            symbolStack.push.apply(
              symbolStack,
              getProductionRhs(production)
                .concat([makeRuleIndexFlag(ruleIndex, unit), productionEndFlag])
                .reverse()
            );
          }
        } else if (
          isZeroOrMoreSymbol(topSymbol) ||
          isOptionalSymbol(topSymbol)
        ) {
          popSymbolStack();
        } else {
          error = {
            recovery: false,
            ...getParseError(getExpected),
            expected: getExpected(),
            symbol: peekStack(astStack).symbol,
            lexer: lexer.toJSON(),
          };
          if (onErrorRecovery) {
            const recommendedAction = {};
            lexer.stash();
            const nextToken = lexer.lex();
            lexer.stashPop();
            // should delete
            if (
              topSymbol === nextToken.t ||
              predictProductionIndexNextLLK(findSymbolIndex())
            ) {
              recommendedAction.action = "del";
            } else if (error.expected.length) {
              recommendedAction.action = "add";
            }

            const errorNode = new AstNode({
              error,
              type: "token",
              ...error.lexer,
            });
            peekStack(astStack).addChild(errorNode);

            const recovery =
              onErrorRecovery(
                {
                  errorNode,
                  parseTree: getAstRootNode(astStack, getAstRootNode, true),
                },
                recommendedAction
              ) || {};

            const { action } = recovery;

            peekStack(astStack).children.pop();

            if (!action) {
              closeAstWhenError();
              break;
            }

            clearStateMatchCache();

            if (action === "del") {
              error.recovery = true;
              const deleteToken = recoveryTokens.pop();
              deleteToken.recovery = "del";
              token = null;
            } else if (action === "add") {
              error.recovery = true;
              token = {
                ...token,
                token: recovery.token,
                text: recovery.text,
                t: lexer.mapSymbol(recovery.token),
                recovery: "add",
              };
              lexer.pushToken(token);
              pushRecoveryTokens(token);
            }
          } else {
            closeAstWhenError();
            break;
          }
        }
      }

      topSymbol = peekSymbolStack();

      while (topSymbol && typeof topSymbol === "function") {
        if (onAction) {
          onAction({
            token: lexer.getLastToken(),
            action: topSymbol,
            parseTree: getAstRootNode(astStack, transformNode, true),
          });
        }
        popSymbolStack();
        topSymbol = peekSymbolStack();
      }

      if (!symbolStack.length) {
        break;
      }
    }

    if (!error && lexer.getCurrentToken().token !== EOF_TOKEN) {
      // reduction done but still has input
      if (!symbolStack.length) {
        getExpected = () => [EOF_TOKEN];
      }
      error = {
        ...getParseError(getExpected),
        expected: getExpected(),
        symbol: peekStack(astStack)?.symbol,
        lexer: lexer.toJSON(),
      };
      closeAstWhenError();
    }

    const ast = getAstRootNode(astStack, transformNode);

    clearStateMatchCache();

    return {
      ast,
      tokens: lexer.tokens,
      recoveryTokens,
      errorNode,
      error,
      terminalNodes,
    };
  };
  var predictProductionIndexLLK = function (
    { childReverseIndex, ruleIndex },
    fn
  ) {
    const productions = parser.productions;

    if (ruleIndex === -1) {
      const production = productions[0];
      return {
        unit: buildRhsSM(
          parser.getProductionSymbol(production),
          filterRhs(parser.getProductionRhs(production)),
          0
        ),
        ruleIndex: 0,
      };
    }

    let parentSymbolItem = getParentSymbolItem();
    if (!parentSymbolItem) {
      throw new Error("no parent symbol");
    }
    const parentUnit = parentSymbolItem.ruleUnit;
    const { units } = parentUnit;
    let unit = units[units.length - 1 - childReverseIndex];
    const childSymbol = unit.type;

    if (!isSymbol(unit.type)) {
      return null;
    }

    let returnedUnit = unit;

    const { unitType } = unit;
    if (unitType === "zeroOrMore" || unitType === "optional") {
      const newUnit = new SymbolStateUnit(childSymbol, ruleIndex);
      newUnit.end.pushTransition(unit.end);
      if (unitType === "zeroOrMore") {
        returnedUnit = unit.start.transitions[0].to.unit;
      } else {
        returnedUnit = newUnit;
      }
      unit = newUnit;
    } else {
      const alterations = productionsBySymbol[childSymbol];
      if (alterations.ruleIndexes.length <= 1) {
        const ruleIndex = alterations.ruleIndexes[0];
        if (ruleIndex === undefined) {
          throw new Error("no predict!");
        }
        return returnNext(ruleIndex);
      }
    }

    const transitions = unit.start.transitions;

    let maxCount = 0;
    let matchedRuleIndex = -1;

    function returnNext(ruleIndex) {
      return {
        ruleIndex,
        unit: returnedUnit.start.getUnits()[ruleIndex],
      };
    }

    function cacheUnit() {
      const afterUnits = units.slice(units.length - childReverseIndex);
      for (const afterUnit of afterUnits) {
        setStateCacheMatch(afterUnit.start, parentSymbolItem.tokensLength);
      }
    }

    function getStateCacheMatchLocal(state) {
      return getStateCacheMatch(state, parentSymbolItem.tokensLength);
    }

    for (const t of transitions) {
      lexer.stash();
      if (fn) {
        fn();
      }
      const { match, count } = bfsMatch(t.to, getStateCacheMatchLocal);
      lexer.stashPop();
      if (match) {
        //console.log('match', productions[t.to.unit.ruleIndex] + '');
        cacheUnit();
        return returnNext(t.to.unit.ruleIndex);
      }
      if (maxCount < count) {
        maxCount = count;
        matchedRuleIndex = t.to.unit.ruleIndex;
      }
    }

    if (matchedRuleIndex !== -1) {
      //console.log('matchedRuleIndex', productions[matchedRuleIndex] + '');
      cacheUnit();
      return returnNext(matchedRuleIndex);
    }
    return null;
  };
  var predictProductionIndexNextLLK = function (arg) {
    return predictProductionIndexLLK(arg, () => lexer.lex());
  };
  var setStateCacheMatch = function (state, tokensLength) {
    let holder = cachedStateMatchMap.get(state);
    if (!holder) {
      holder = new Set();
      cachedStateMatchMap.set(state, holder);
    }
    holder.add(tokensLength);
  };
  var getStateCacheMatch = function (state, tokensLength) {
    return false;
    const holder = cachedStateMatchMap.get(state);
    return holder?.has(tokensLength);
  };
  var clearStateMatchCache = function () {
    cachedStateMatchMap = new Map();
  };
  var bfsMatch = function (startState, getStateCacheMatchLocal) {
    let reachableStates = [startState];
    let ret = {};
    let count = 0;
    while (1) {
      reachableStates = getNextReachableStates(
        reachableStates,
        ret,
        getStateCacheMatchLocal
      );
      if (reachableStates.length) {
        lexer.lex();
        count++;
      } else {
        break;
      }
    }
    if (ret.matchedInput) {
      return {
        match: true,
        count,
      };
    }
    return { match: false, count };
  };
  var getNextReachableStates = function (
    reachableStates,
    ret,
    getStateCacheMatchLocal
  ) {
    const stack = [];
    const newReachableStates = [];
    const encountered = new Set();
    for (const currentState of reachableStates) {
      stack.push(currentState);
      let state;
      while (stack.length) {
        state = stack.pop();
        if (encountered.has(state)) {
          continue;
        }
        encountered.add(state);
        if (getStateCacheMatchLocal(state)) {
          ret.matchedInput = true;
          return [];
        }
        if (
          !state.transitions.length &&
          lexer.getCurrentToken().token === Lexer.STATIC.EOF_TOKEN
        ) {
          ret.matchedInput = true;
          return [];
        }
        let finded;
        for (const t of state.transitions) {
          const find = t.perform();
          finded = finded || !!find;
          if (find) {
            if (find.count) {
              newReachableStates.push(t.to);
            } else {
              stack.push(t.to);
            }
          }
        }
      }
    }
    return newReachableStates;
  };
  var initLLK = function () {
    const { productions } = parser;
    for (let i = 0; i < productions.length; i++) {
      const p = productions[i];
      const symbol = parser.getProductionSymbol(p);
      productionsBySymbol[symbol] = productionsBySymbol[symbol] || {
        ruleIndexes: [],
      };
      productionsBySymbol[symbol][i] = p;
      productionsBySymbol[symbol].ruleIndexes.push(i);
    }
  };
  var isSymbol = function (s) {
    return !!productionsBySymbol[s];
  };
  var createTokenMatcher = (token) => {
    const fn = () => {
      const currentToken = lexer.getCurrentToken();
      return currentToken.t === token ? { count: 1 } : false;
    };
    fn.token = token;
    return fn;
  };
  var getParentSymbolItem = function () {
    let parentSymbolItem;

    for (let i = symbolStack.length - 1; i >= 0; i--) {
      const s = symbolStack[i];
      if (s?.type === "rule") {
        parentSymbolItem = s;
        break;
      }
    }

    return parentSymbolItem;
  };
  var findExpectedTokenFromStateMachine = function (
    { childReverseIndex },
    stack = new Set()
  ) {
    const ret = new Set();
    const { ruleUnit: parentUnit } = getParentSymbolItem();
    const { units } = parentUnit;
    let unit = units[units.length - 1 - childReverseIndex];
    const states = [unit.start];
    while (states.length) {
      const state = states.pop();
      if (stack.has(state)) {
        continue;
      }
      stack.add(state);
      for (const t of state.transitions) {
        if (t.condition?.token) {
          ret.add(t.condition.token);
          continue;
        }
        if (t.to) {
          states.push(t.to);
        }
      }
    }
    return Array.from(ret);
  };
  var buildStateMachine = function () {
    const productions = parser.productions;
    for (let i = 0; i < productions.length; i++) {
      const p = productions[i];
      const symbol = parser.getProductionSymbol(p);

      productionsBySymbol[symbol] = productionsBySymbol[symbol] || {
        ruleIndexes: [],
      };
      productionsBySymbol[symbol][i] = p;
      productionsBySymbol[symbol].ruleIndexes.push(i);
    }
  };
  var buildRhsSM = function (symbol, rhs, ruleIndex) {
    function getUnit(rr) {
      if (isSymbol(rr)) {
        return new SymbolStateUnit(rr, ruleIndex);
      }
      const unit = new StateUnit(rr, ruleIndex);
      unit.start.pushTransition(unit.end, createTokenMatcher(rr));
      return unit;
    }

    const units = [];
    let i = -1;
    for (const r of rhs) {
      if (typeof r !== "string") {
        continue;
      }
      ++i;
      let finalUnit;
      if (isOptionalSymbol(r)) {
        const rr = r.slice(0, -1);
        const unit = getUnit(rr);
        finalUnit = new StateUnit(rr, ruleIndex);
        finalUnit.unitType = "optional";
        finalUnit.start.pushTransition(unit.start);
        finalUnit.start.pushTransition(finalUnit.end);
        unit.end.pushTransition(finalUnit.end);
      } else if (isZeroOrMoreSymbol(r)) {
        const rr = r.slice(0, -1);
        const unit = getUnit(rr);
        finalUnit = new StateUnit(rr, ruleIndex);
        finalUnit.unitType = "zeroOrMore";
        finalUnit.start.pushTransition(unit.start);
        unit.start.pushTransition(finalUnit.end);
        unit.end.pushTransition(unit.start);
      } else {
        finalUnit = getUnit(r);
      }
      units.push(finalUnit);
    }
    return concatUnits(symbol, units, ruleIndex);
  };
  var SymbolState = class SymbolState {
    constructor(symbol, type, unit) {
      this.type = type;
      this.symbol = symbol;
      let transitions = undefined;
      this._transitions = [];
      this.allTranstions = [];
      this.unit = unit;
      this.emptyRuleIndex = undefined;
      this.units = {};
      Object.defineProperty(this, "transitions", {
        get: () => {
          if (!transitions) {
            transitions = this._transitions.concat();
            const myProductions = productionsBySymbol[symbol];
            for (const i of myProductions.ruleIndexes) {
              const p = myProductions[i];
              const rhs = parser.getProductionRhs(p);
              const rootSymbolUnit = buildRhsSM(symbol, rhs, i);
              this.units[i] = rootSymbolUnit;
              transitions.push(new Transition(rootSymbolUnit.start));
              rootSymbolUnit.end.pushTransition(unit.end);
            }
            this.allTranstions = transitions;
          }
          return transitions;
        },
      });
    }

    getTransitions() {
      return this["transitions"];
    }

    getUnits() {
      this.getTransitions();
      return this.units;
    }

    pushTransition(endState, condition) {
      this._transitions.push(new Transition(endState, condition));
    }
  };
  var SymbolStateUnit = class SymbolStateUnit {
    unitType = "symbol";
    constructor(type, ruleIndex) {
      this.ruleIndex = ruleIndex;
      this.type = type;
      this.end = new State(`endOf${type}`, this);
      this.start = new SymbolState(type, `startOf${type}`, this);
    }
  };
  var State = class State {
    constructor(type, unit) {
      this.type = type;
      this.unit = unit;
      this.transitions = [];
    }
    pushTransition(endState, condition) {
      this.transitions.push(new Transition(endState, condition));
    }
  };
  var concatUnits = function (type, us, ruleIndex) {
    const l = us.length;
    for (let i = 0; i < l - 1; i++) {
      const first = us[i];
      const s = us[i + 1];
      first.end.pushTransition(s.start);
    }
    const ret = new RootSymbolUnit(type, ruleIndex);
    if (l >= 1) {
      ret.start = us[0].start;
      ret.end = us[l - 1].end;
    } else {
      ret.start = new State(`startOf${type}`, ret);
      ret.end = new State(`endOf${type}`, ret);
      ret.start.pushTransition(ret.end);
    }
    ret.units = us;
    return ret;
  };
  var StateUnit = class StateUnit {
    units = undefined;
    unitType = "token";
    constructor(type, ruleIndex) {
      this.type = type;
      this.ruleIndex = ruleIndex;
      this.start = new State(`startOf${type}`, this);
      this.end = new State(`endOf${type}`, this);
    }
  };
  var Transition = class Transition {
    constructor(to, condition) {
      this.to = to;
      this.condition = condition;
    }
    perform() {
      if (this.condition) {
        const ret = this.condition();
        if (ret === true) {
          return {
            count: 0,
          };
        }
        return ret;
      }
      return {
        count: 0,
      };
    }
  };
  var RootSymbolUnit = class RootSymbolUnit {
    units = undefined;
    start = undefined;
    end = undefined;
    unitType = "rootSymbol";
    constructor(type, ruleIndex) {
      this.type = type;
      this.ruleIndex = ruleIndex;
    }
  };
  initLLK();
  parser.parse = parse;
  return parser;
})();

if (typeof module !== "undefined") {
  module.exports = $parser;
}
