formula ::= exp
exp_p_end ::= '(' exp ')'
exp_p_end ::= 'NUMBER'
exp_p_end ::= 'STRING'
exp_p_end ::= 'LOGIC'
exp_p_end ::= 'ERROR'
exp_p_end ::= reference
referenceItem ::= 'CELL'
referenceItem ::= 'NAME'
referenceItem ::= structureReference
reference_p_end ::= referenceItem
exp_p_end ::= function
exp_p_end ::= array
arrayElement ::= 'STRING'
arrayElement ::= 'NUMBER'
arrayElement ::= 'LOGIC'
arrayElement ::= 'ERROR'
arrayElementPart ::= 'ARRAY_SEPARATOR' arrayElement
zeroMore_arrayElementPart_1 ::= zeroMore_arrayElementPart_1 arrayElementPart
zeroMore_arrayElementPart_1 ::=
array ::= '{' arrayElement zeroMore_arrayElementPart_1 '}'
function ::= 'FUNCTION' '(' arguments ')'
zeroMore_argumentPart_2 ::= zeroMore_argumentPart_2 argumentPart
zeroMore_argumentPart_2 ::=
arguments ::= exp zeroMore_argumentPart_2
arguments ::= zeroMore_argumentPart_2
argumentPart ::= 'ARGUMENT_SEPARATOR' exp
argumentPart ::= 'ARGUMENT_SEPARATOR'
structureReference ::= 'TABLE_NAME' tableSpecifier
structureReference ::= tableSpecifier
tableSpecifier ::= 'TABLE_ITEM_SPECIFIER'
tableSpecifier ::= '[' tableSpecifierInner ']'
tableThisRow ::= 'TABLE_@'
tableThisRow ::= 'TABLE_@' 'TABLE_COLUMN_SPECIFIER'
tableSpecifierInner ::= tableThisRow
tableSpecifierInner ::= tableColumnSpecifier
tableSpecifierItem ::= 'TABLE_COLUMN_SPECIFIER'
tableSpecifierItem ::= 'TABLE_ITEM_SPECIFIER'
zeroMore_tableSpecifierItemPart_3 ::= zeroMore_tableSpecifierItemPart_3 tableSpecifierItemPart
zeroMore_tableSpecifierItemPart_3 ::=
tableColumnSpecifier ::= tableSpecifierItem zeroMore_tableSpecifierItemPart_3
tableSpecifierItemPart ::= 'SPECIFIER_SEPARATOR' tableSpecifierItem
exp ::= exp_p_2
exp ::= exp '=' exp_p_2
exp ::= exp '<=' exp_p_2
exp ::= exp '>=' exp_p_2
exp ::= exp '<>' exp_p_2
exp ::= exp '>' exp_p_2
exp ::= exp '<' exp_p_2
exp_p_2 ::= exp_p_3
exp_p_2 ::= exp_p_2 '&' exp_p_3
exp_p_3 ::= exp_p_4
exp_p_3 ::= exp_p_3 '+' exp_p_4
exp_p_3 ::= exp_p_3 '-' exp_p_4
exp_p_4 ::= exp_p_5
exp_p_4 ::= exp_p_4 '*' exp_p_5
exp_p_4 ::= exp_p_4 '/' exp_p_5
exp_p_5 ::= exp_p_6
exp_p_5 ::= exp_p_5 '^' exp_p_6
exp_p_6 ::= exp_p_7
exp_p_6 ::= exp_p_6 '%'
exp_p_7 ::= exp_p_8
exp_p_7 ::= '+' exp_p_7
exp_p_7 ::= '-' exp_p_7
exp_p_8 ::= exp_p_end
exp_p_8 ::= '@' exp_p_8
reference ::= reference_p_10
reference ::= reference 'REF_UNION_OPERATOR' reference_p_10
reference_p_10 ::= reference_p_11
reference_p_10 ::= reference_p_10 reference_p_11
reference_p_11 ::= reference_p_end
reference_p_11 ::= reference_p_11 'REF_RANGE_OPERATOR' reference_p_end