exp_p_end ::= 'NUMBER'
exp_p_end ::= '(' exp ')'
exp ::= exp_p_2
exp ::= exp '+' exp_p_2
exp ::= exp '-' exp_p_2
exp_p_2 ::= exp_p_3
exp_p_2 ::= exp_p_2 '*' exp_p_3
exp_p_2 ::= exp_p_2 '/' exp_p_3
exp_p_3 ::= exp_p_4
exp_p_3 ::= exp_p_4 '^' exp_p_3
exp_p_4 ::= exp_p_end
exp_p_4 ::= '-' exp_p_4