/*
Generated By kison v0.5.21

Generate time: Thu Nov 04 2021 11:57:57 GMT+0800 (中国标准时间)
*/
var $parser = (function (undefined) {
  var BaseAstNode = class BaseAstNode {
    start = 0;
    end = 0;
    firstLine = 0;
    lastLine = 0;
    firstColumn = 0;
    lastColumn = 0;

    toJSON() {
      const ret = {};

      for (const k of Object.keys(this)) {
        if (k !== 'parent' && k !== 't') {
          const v = this[k];

          if (v !== undefined) {
            ret[k] = v;
          }
        }
      }

      return ret;
    }
  };
  var AstSymbolNode = class AstSymbolNode extends BaseAstNode {
    symbol = '';
    type = 'symbol';
    children = [];
    ruleIndex = -1;
    internalRuleIndex = -1;

    constructor(params) {
      super();
      Object.assign(this, params);

      if (params.children) {
        this.setChildren(params.children);
      }

      if (params.internalRuleIndex !== undefined) {
        this.ruleIndex = productionRuleIndexMap[this.internalRuleIndex];
      }
    }

    addChild(c) {
      this.addChildren([c]);
    }

    addChildren(cs) {
      this.children = this.children || [];
      this.children.push(...cs);
      this.setChildren(this.children);
    }

    refreshChildren() {
      this.setChildren(this.children);
    }

    setChildren(cs) {
      if (!cs.length) {
        this.children = [];
        return;
      }

      const first = cs[0];
      const last = cs[cs.length - 1];
      this.start = first.start;
      this.end = last.end;
      this.firstLine = first.firstLine;
      this.lastLine = last.lastLine;
      this.firstColumn = first.firstColumn;
      this.lastColumn = last.lastColumn;
      this.children = cs;

      for (const c of cs) {
        c.parent = this;
      }
    }
  };
  var AstTokenNode = class AstTokenNode extends BaseAstNode {
    token = '';
    t = '';
    type = 'token';

    constructor(params) {
      super();
      Object.assign(this, params);
    }
  };
  var AstErrorNode = class AstErrorNode extends AstTokenNode {
    constructor(ErrorTokenParams) {
      super(ErrorTokenParams);
      Object.assign(ErrorTokenParams);
    }
  };
  var checkLLEndError = function (getExpected, ret) {
    const { EOF_TOKEN } = Lexer.STATIC;

    if (!ret.error && lexer.getCurrentToken().token !== EOF_TOKEN) {
      var _peekStack;

      // reduction done but still has input
      if (!symbolStack.length) {
        getExpected = () => [EOF_TOKEN];

        lexer.lex();
      }

      ret.error = {
        ...getParseError(getExpected),
        expected: getExpected(),
        symbol:
          (_peekStack = peekStack(astStack)) === null || _peekStack === void 0
            ? void 0
            : _peekStack.symbol,
        lexer: lexer.toJSON(),
      };
      ret.errorNode = closeAstWhenError(ret.error, astStack);
    }

    return ret;
  };
  var takeCareLLError = function (
    getExpected,
    onErrorRecovery,
    topSymbol,
    shouldDelete,
    transformNode,
    recoveryTokens,
    ret,
  ) {
    ret.error = {
      recovery: false,
      ...getParseError(getExpected),
      expected: getExpected(),
      symbol: peekStack(astStack).symbol,
      lexer: lexer.toJSON(),
    };

    if (onErrorRecovery) {
      const recommendedAction = {};
      lexer.stash();
      const nextToken = lexer.lex();
      lexer.stashPop(); // should delete

      if (topSymbol === nextToken.t || shouldDelete(nextToken)) {
        recommendedAction.action = 'del';
      } else if (ret.error.expected.length) {
        recommendedAction.action = 'add';
      }

      const localErrorNode = new AstErrorNode({
        error: ret.error,
        ...ret.error.lexer,
      });
      peekStack(astStack).addChild(localErrorNode);
      const recovery =
        onErrorRecovery(
          {
            errorNode: localErrorNode,
            parseTree: getAstRootNode(astStack, transformNode, true),
          },
          recommendedAction,
        ) || {};
      const { action } = recovery;
      peekStack(astStack).children.pop();

      if (!action) {
        ret.errorNode = closeAstWhenError(ret.error, astStack);
        ret.breakToEnd = true;
        return ret;
      }

      if (action === 'del') {
        ret.error.recovery = true;
        const deleteToken = recoveryTokens.pop();
        deleteToken.recovery = 'del';
        ret.token = undefined;
      } else if (action === 'add') {
        ret.error.recovery = true;
        ret.token = {
          ...ret.token,
          token: recovery.token,
          text: recovery.text,
          t: lexer.mapSymbol(recovery.token),
          recovery: 'add',
        };
        lexer.pushToken(ret.token);
        pushRecoveryTokens(recoveryTokens, ret.token);
      }
    } else {
      ret.errorNode = closeAstWhenError(ret.error, astStack);
      ret.breakToEnd = true;
    }

    return ret;
  };
  var takeCareLLAction = function (popSymbolStack, peekSymbolStack) {
    let topSymbol = peekSymbolStack();

    while (topSymbol && typeof topSymbol === 'function') {
      topSymbol.call(parser);
      popSymbolStack();
      topSymbol = peekSymbolStack();
    }

    return topSymbol;
  };
  var reduceLLAction = function (topSymbol, popSymbolStack, peekSymbolStack) {
    while (isProductionEndFlag(topSymbol) || isAddAstNodeFlag(topSymbol)) {
      let ast = astStack.pop();

      if (isAddAstNodeFlag(topSymbol)) {
        const stackTop = peekStack(astStack);
        const wrap = new AstSymbolNode({
          id: ++globalSymbolNodeId,
          symbol: ast.symbol,
          children: [ast],
          internalRuleIndex: ast.internalRuleIndex,
        });
        stackTop.children.pop();
        stackTop.addChild(wrap);
        astStack.push(wrap);
      } else {
        ast.refreshChildren();
        const ruleIndex = ast.internalRuleIndex;
        const production = parser.productions[ruleIndex];
        const action = parser.getProductionAction(production);

        if (action) {
          action.call(parser);
        }
      }

      popSymbolStack();
      topSymbol = peekSymbolStack();

      if (!topSymbol) {
        break;
      }
    }

    return topSymbol;
  };
  var prepareLLParse = function () {
    globalSymbolNodeId = 0;
    parser.userData = {};
    symbolStack = [];
    astStack = [
      new AstSymbolNode({
        id: 0,
        children: [],
      }),
    ];
  };
  var endLLParse = function () {
    globalSymbolNodeId = 0;
    parser.userData = {};
    symbolStack = [];
    astStack = [];
  };
  var filterRhs = function (rhs) {
    const ret = [];

    for (const r of rhs) {
      if (typeof r === 'string') {
        ret.push(r);
      }
    }

    return ret;
  };
  var isExtraAstNode = function (ast) {
    return ast.children && !ast.children.length;
  };
  var peekStack = function (stack, n = 1) {
    return stack[stack.length - n];
  };
  var getOriginalSymbol = function (s) {
    let uncompressed = lexer.mapReverseSymbol(s);
    return parser.prioritySymbolMap[uncompressed] || uncompressed;
  };
  var closeAstWhenError = function (error, astStack) {
    const errorNode = new AstErrorNode({
      error,
      ...error.lexer,
    });
    const top = peekStack(astStack);

    if (top.type === 'symbol') {
      top.addChild(errorNode);
    }

    while (astStack.length > 1) {
      const ast = astStack.pop();

      if (ast && ast.type === 'symbol' && isExtraAstNode(ast)) {
        const topAst = peekStack(astStack);

        if (topAst.type === 'symbol') {
          topAst.children.pop();
          topAst.addChildren(ast.children);
        }
      }
    }

    return errorNode;
  };
  var pushRecoveryTokens = function (recoveryTokens, token) {
    var _recoveryTokens;

    const { EOF_TOKEN } = Lexer.STATIC;
    let eof;

    if (
      ((_recoveryTokens = recoveryTokens[recoveryTokens.length - 1]) === null ||
      _recoveryTokens === void 0
        ? void 0
        : _recoveryTokens.token) === EOF_TOKEN
    ) {
      eof = recoveryTokens.pop();
    }

    recoveryTokens.push(token);

    if (eof && token.token !== EOF_TOKEN) {
      recoveryTokens.push(eof);
    }
  };
  var getParseError = function (getExpected) {
    const expected = getExpected();
    const tips = [];

    if (expected.length) {
      tips.push("'" + expected.join("', '") + "' expected.");
    }

    tips.push("current token: '" + lexer.getCurrentToken().token + "'.");
    const tip = tips.join('\n');
    return {
      errorMessage: [
        'syntax error at line ' +
          lexer.lineNumber +
          ':\n' +
          lexer.showDebugInfo(),
        ...tips,
      ].join('\n'),
      tip,
    };
  };
  var cleanAst = function (ast, transformNode) {
    if (!transformNode) {
      return ast;
    }

    if (ast.children) {
      let children;
      let childrenChanged;

      while (true) {
        let changed = false;
        let index = 0;
        children = [];

        for (const c of ast.children) {
          const node = transformNode({
            node: c,
            index,
            parent: ast,
            defaultTransformNode: defaultTransformAstNode,
          });

          if (Array.isArray(node)) {
            children.push(...node);
          } else if (node) {
            children.push(node);
          }

          changed = changed || node !== c;
          index++;
        }

        if (!changed) {
          break;
        } else {
          ast.setChildren(children);
          childrenChanged = true;
        }
      }

      if (childrenChanged && ast.parent) {
        cleanAst(ast.parent, transformNode);
      } else {
        for (const c of children) {
          if (c.type === 'symbol') {
            cleanAst(c, transformNode);
          }
        }
      }
    }

    return ast;
  };
  var getAstRootNode = function (astStack, transformNode, raw) {
    var _ast, _ast$children;

    let ast = astStack[0];

    if (!ast) {
      return ast;
    }

    if (ast.type !== 'symbol') {
      return ast;
    }

    ast =
      (_ast = ast) === null || _ast === void 0
        ? void 0
        : (_ast$children = _ast.children) === null || _ast$children === void 0
        ? void 0
        : _ast$children[0];

    if (ast && ast.type === 'symbol' && ast.symbol === START_TAG) {
      var _ast2, _ast2$children;

      ast =
        (_ast2 = ast) === null || _ast2 === void 0
          ? void 0
          : (_ast2$children = _ast2.children) === null ||
            _ast2$children === void 0
          ? void 0
          : _ast2$children[0];
    }

    if (ast) {
      ast.parent = undefined;
    }

    if (raw) {
      return ast;
    }

    if (ast && ast.type === 'token') {
      return ast;
    }

    return ast && cleanAst(ast, transformNode);
  };
  var defaultTransformAstNode = function ({ node, parent }) {
    if (node.type === 'token' || node.symbol !== parent.symbol) {
      return node;
    }

    if (node.label || parent.label) {
      if (node.label !== parent.label) {
        return node;
      }
    }

    if (parent.children.length === 1) {
      return node.children;
    }

    return node;
  };
  var isAddAstNodeFlag = function (t) {
    return t === productionAddAstNodeFlag;
  };
  var isProductionEndFlag = function (t) {
    return t === productionEndFlag;
  };
  var isZeroOrMoreSymbol = function (s) {
    return (
      typeof s === 'string' && s !== '*?' && s.length > 1 && !!s.match(/\*\??$/)
    );
  };
  var isOneOrMoreSymbol = function (s) {
    return (
      typeof s === 'string' && s !== '+?' && s.length > 1 && !!s.match(/\+\??$/)
    );
  };
  var isLazySymbol = function (s) {
    const match = typeof s === 'string' && s.match(/(\*|\+|\?)\?$/);
    return match && s.length !== 2;
  };
  var isOptionalSymbol = function (s) {
    return typeof s === 'string' && s.length > 1 && !!s.match(/\??\?/);
  };
  var normalizeSymbol = function (s) {
    const ret =
      isOptionalSymbol(s) || isZeroOrMoreSymbol(s) || isOneOrMoreSymbol(s)
        ? s.replace(/(\*|\+|\?)?\??$/, '')
        : s; // ??

    return ret || (s && s.slice(0, -1));
  };
  var VIRTUAL_OPTIONAL_RULE_INDEX = -100;
  var START_TAG = '$START';
  var smUnitBySymbol = {};
  var productionSkipAstNodeSet = undefined;
  var symbolStack = [{}];
  var astStack = [];
  var productionsBySymbol = {};
  var productionAddAstNodeFlag = 1;
  var productionEndFlag = 2;
  var globalSymbolNodeId = 0;
  var Lexer = function (cfg) {
    this.nextTokens = [];

    if (Lexer.supportSticky === undefined) {
      try {
        Lexer.supportSticky = typeof /(?:)/.sticky == 'boolean';
      } catch (e) {
        Lexer.supportSticky = false;
      }
    }

    const lexerRuleIndexMap = (this.lexerRuleIndexMap = {
      token: 0,
      regexp: 1,
      action: 2,
      filter: 3,
      state: 4,
      channel: 5,
    });
    const STATIC = Lexer.STATIC;
    this.tokenSet = new Set([STATIC.EOF_TOKEN, STATIC.UNKNOWN_TOKEN]);
    this.rules = [];
    this.defaultEnv = undefined;
    Object.assign(this, cfg);
    this.rules = this.rules.concat();
    this.regexpIndex = this.isCompress
      ? this.lexerRuleIndexMap.regexp
      : 'regexp';
    this.getRuleItem = this.isCompress
      ? this.getRuleItemCompress
      : this.getRuleItemNoCompress;
    this.transformRules();
    this.userData = {};
    const errorRule = (this.errorRule = {
      regexp: this.matchAny,
      token: Lexer.STATIC.UNKNOWN_TOKEN,
    });

    for (const rule of this.rules) {
      const token = this.getRuleItem(rule, 'token');

      if (token) {
        this.tokenSet.add(token);
      }
    }

    if (this.isCompress) {
      const errorRuleCompress = (this.errorRule = []);
      errorRuleCompress[lexerRuleIndexMap.token] = errorRule.token;
      errorRuleCompress[lexerRuleIndexMap.regexp] = errorRule.regexp;
    }

    this.resetInput(this.input);
    this.options = {};
  };
  Lexer.prototype = {
    transformRegExp: function (obj, p, disableSticky) {
      const pattern = obj[p];

      if (pattern.test) {
        let source = pattern.source;

        if (source.startsWith('^')) {
          source = source.slice(1);
        }

        var flags = Lexer.supportSticky && !disableSticky ? 'gy' : 'g';
        if (pattern.multiline) flags += 'm';
        if (pattern.ignoreCase) flags += 'i';
        if (pattern.unicode) flags += 'u';
        obj[p] = new RegExp(source, flags);
      } else if (typeof pattern === 'object') {
        for (const k of Object.keys(pattern)) {
          this.transformRegExp(pattern, k);
        }
      }
    },
    hasToken: function (t) {
      return this.tokenSet.has(t);
    },
    transformRules: function () {
      if (Lexer.supportSticky) {
        const { regexpIndex } = this;

        for (const r of this.rules) {
          this.transformRegExp(r, regexpIndex);
        }
      }
    },
    matchAny: function () {
      return this.end < this.input.length ? this.input.charAt(this.end) : false;
    },
    addRule: function (rule) {
      this.rules.push(rule);
      const token = this.getRuleItem(rule, 'token');

      if (token) {
        this.tokenSet.add(token);
      }
    },
    resetInput: function (input) {
      this.token = '';
      this.nextTokens = [];
      this.tokens = [];
      this.userData = {};
      this.input = input;
      this.matched = '';
      this.stateStack = [Lexer.STATIC.INITIAL_STATE];
      this.match = '';
      this.text = '';
      this.firstLine = 1;
      this.lineNumber = 1;
      this.lastLine = 1;
      this.start = 0;
      this.end = 0;
      this.firstColumn = 1;
      this.lastColumn = 1;
    },
    getRuleItemNoCompress: function (rule, itemType) {
      return rule[itemType];
    },
    getRuleItemCompress: function (rule, itemType) {
      return rule[this.lexerRuleIndexMap[itemType]];
    },
    getCurrentRules: function () {
      var currentState = this.stateStack[this.stateStack.length - 1],
        rules = [];

      for (const r of this.rules) {
        var filter = this.getRuleItem(r, 'filter');

        if (filter) {
          if (filter.call(this)) {
            rules.push(r);
          }

          continue;
        }

        var state = this.getRuleItem(r, 'state');

        if (!state) {
          if (currentState === Lexer.STATIC.INITIAL_STATE) {
            rules.push(r);
          }
        } else if (state.indexOf(currentState) !== -1) {
          rules.push(r);
        }
      }

      rules.push(this.errorRule);
      return rules;
    },
    peekState: function (n = 1) {
      return this.mapReverseState(this.stateStack[this.stateStack.length - n]);
    },
    pushState: function (state) {
      this.stateStack.push(this.mapState(state));
    },
    popState: function (num = 1) {
      var ret;

      while (num--) {
        ret = this.stateStack.pop();
      }

      return ret && this.mapReverseState(ret);
    },
    showDebugInfo: function () {
      var { DEBUG_CONTEXT_LIMIT } = Lexer.STATIC;
      var { matched, match, input } = this;
      matched = matched.slice(0, matched.length - match.length);
      var past =
          (matched.length > DEBUG_CONTEXT_LIMIT ? '...' : '') +
          matched
            .slice(0 - DEBUG_CONTEXT_LIMIT)
            .split('\n')
            .join(' '),
        next = match + input.slice(this.end); //#JSCOVERAGE_ENDIF

      next =
        next.slice(0, DEBUG_CONTEXT_LIMIT).split('\n').join(' ') +
        (next.length > DEBUG_CONTEXT_LIMIT ? '...' : '');
      return past + next + '\n' + new Array(past.length + 1).join('-') + '^';
    },
    mapSymbol: function (t) {
      return (this.symbolMap && this.symbolMap[t]) || t;
    },
    mapReverseSymbol: function (rs) {
      var { symbolMap, reverseSymbolMap } = this;

      if (!reverseSymbolMap && symbolMap) {
        reverseSymbolMap = this.reverseSymbolMap = {};

        for (var i of Object.keys(symbolMap)) {
          reverseSymbolMap[symbolMap[i]] = i;
        }
      }

      const nrs = normalizeSymbol(rs);

      if (nrs === rs) {
        return (reverseSymbolMap && reverseSymbolMap[rs]) || rs;
      } else {
        return (
          ((reverseSymbolMap && reverseSymbolMap[nrs]) || nrs) + rs.slice(-1)
        );
      }
    },
    mapState: function (t) {
      return (this.stateMap && this.stateMap[t]) || t;
    },
    mapReverseState: function (rs) {
      var { stateMap, reverseStateMap } = this;

      if (!reverseStateMap && stateMap) {
        reverseStateMap = this.reverseStateMap = {};

        for (var i of Object.keys(stateMap)) {
          reverseStateMap[stateMap[i]] = i;
        }
      }

      return (reverseStateMap && reverseStateMap[rs]) || rs;
    },
    toJSON: function () {
      const currentToken = this.getCurrentToken();
      return {
        t: currentToken.t,
        text: currentToken.text,
        firstLine: currentToken.firstLine,
        firstColumn: currentToken.firstColumn,
        lastLine: currentToken.lastLine,
        lastColumn: currentToken.lastColumn,
        token: currentToken.token,
        start: currentToken.start,
        end: currentToken.end,
      };
    },
    stash: function () {
      this.stashIndex = this.tokens.length;
    },
    stashPop: function () {
      this.nextTokens = [
        ...this.tokens.slice(this.stashIndex),
        ...this.nextTokens,
      ];
      this.tokens.length = this.stashIndex;
    },
    matchRegExp: function (regexp) {
      if (typeof regexp !== 'function') {
        regexp.lastIndex = this.end;
        const ret = regexp.exec(this.input);

        if (ret && ret.index !== this.end) {
          return null;
        }

        return ret;
      }

      return regexp.call(this, this);
    },
    pushToken: function (token) {
      var _tokens;

      const tokens = this.tokens;

      if (
        ((_tokens = tokens[tokens.length - 1]) === null || _tokens === void 0
          ? void 0
          : _tokens.token) === Lexer.STATIC.EOF_TOKEN
      ) {
        tokens.pop();
      }

      tokens.push(token);
    },
    lex: function () {
      const { EOF_TOKEN } = Lexer.STATIC;
      const token = this.nextToken();
      const tokens = this.tokens;
      const lastToken = tokens[tokens.length - 1];

      if (
        lastToken &&
        token.token === EOF_TOKEN &&
        lastToken.token === EOF_TOKEN
      ) {
        return token;
      }

      this.tokens.push(token);

      if (token.channel || !token.token) {
        return this.lex();
      }

      return token;
    },
    getCurrentToken: function () {
      if (this.tokens[this.tokens.length - 1]) {
        return this.tokens[this.tokens.length - 1];
      }

      return this.lex();
    },
    getLastToken: function () {
      return this.tokens[this.tokens.length - 2] || this.getCurrentToken();
    },
    nextChar: function (index = 0) {
      return this.getChar(this.end + index);
    },
    nextCharCode: function (index = 0) {
      return this.getCharCode(this.end + index);
    },
    nextStartsWith: function (search) {
      let { input, end } = this;
      const l = search.length;

      for (let i = 0; i < l; i++) {
        if (input.charAt(end++) !== search.charAt(i)) {
          return false;
        }
      }

      return true;
    },
    nextCharAt: function (index) {
      return this.input.charAt(this.end + index);
    },
    nextLength: function () {
      return this.input.length - this.end;
    },
    getChar: function (index = 0) {
      if (this.options.unicode) {
        const code = this.input.codePointAt(index);

        if (code === undefined || isNaN(code)) {
          return '';
        }

        return String.fromCodePoint(code);
      }

      return this.input.charAt(index);
    },
    getCharCode: function (index = 0) {
      if (this.options.unicode) {
        return this.input.codePointAt(index);
      }

      return this.input.charCodeAt(index);
    },
    getTokensLength: function () {
      return this.tokens.length;
    },
    nextToken: function () {
      if (this.nextTokens.length) {
        return this.nextTokens.shift();
      }

      var i,
        rule,
        m,
        ret,
        lines,
        rules = this.getCurrentRules();
      var { input } = this;
      var { env = this.defaultEnv } = this.options;
      this.match = this.text = '';

      if (this.end >= input.length) {
        this.token = Lexer.STATIC.EOF_TOKEN;
        this.start = this.end;
        this.firstLine = this.lastLine;
        this.firstColumn = this.lastColumn;
        return {
          text: '',
          t: this.mapSymbol(this.token),
          token: this.token,
          start: this.start,
          end: this.end,
          firstLine: this.firstLine,
          firstColumn: this.firstColumn,
          lastLine: this.lastLine,
          lastColumn: this.lastColumn,
        };
      }

      for (i = 0; i < rules.length; i++) {
        rule = rules[i];
        var regexp = this.getRuleItem(rule, 'regexp'),
          token = this.getRuleItem(rule, 'token'),
          channel = this.getRuleItem(rule, 'channel'),
          action = this.getRuleItem(rule, 'action');

        if (
          typeof regexp !== 'function' &&
          regexp &&
          env &&
          typeof regexp.test !== 'function'
        ) {
          regexp = regexp[env];
        }

        if (!regexp) {
          continue;
        } //#JSCOVERAGE_ENDIF

        if ((m = this.matchRegExp(regexp))) {
          this.start = this.end;
          this.end += m[0].length;
          lines = m[0].split('\n');
          lines.shift();
          this.lineNumber += lines.length;
          const position = {
            start: this.start,
            end: this.end,
            firstLine: this.lastLine,
            lastLine: this.lineNumber,
            firstColumn: this.lastColumn,
            lastColumn: lines.length
              ? lines[lines.length - 1].length + 1
              : this.lastColumn + m[0].length,
          };
          Object.assign(this, position);
          var match; // for error report

          match = this.match = m[0]; // all matches

          this.matches = m; // may change by user

          this.text = match; // matched content utils now

          this.matched += match;
          ret = action && action.call(this);

          if (ret === undefined) {
            ret = token;
          } else {
            ret = this.mapSymbol(ret);
          }

          if (ret) {
            this.token = this.mapReverseSymbol(ret);
            return {
              text: this.text,
              channel,
              token: this.token,
              t: ret,
              ...position,
            };
          } else {
            // ignore
            return this.nextToken();
          }
        }
      }

      throw new Error('no match lexer');
    },
  };
  Lexer.STATIC = {
    INITIAL_STATE: 'I',
    DEBUG_CONTEXT_LIMIT: 20,
    EOF_TOKEN: '$EOF',
    UNKNOWN_TOKEN: '$UNKNOWN',
  };
  var lexer = new Lexer({
    rules: [
      [
        undefined,
        /[\s\S]*?(?={{)/g,
        function () {
          var self = this,
            text = self.text,
            m,
            n = 0;

          if ((m = text.match(/\\+$/))) {
            n = m[0].length;
          }
          if (n % 2) {
            self.pushState('et');
            text = text.slice(0, -1);
          } else {
            self.pushState('t');
          }
          if (n) {
            text = text.replace(/\\+$/g, function (m) {
              return new Array(m.length / 2 + 1).join('\\');
            });
          }
          // https://github.com/kissyteam/kissy/issues/330
          // return even empty
          self.text = text;
          return 'CONTENT';
        },
      ],
      ['a', /[\s\S]+/g],
      [
        'a',
        /[\s\S]{2,}?(?:(?={{)|$)/g,
        function () {
          this.popState();
        },
        undefined,
        ['a'],
      ],
      [
        'b',
        /{{{?(?:#|@)/g,
        function () {
          var self = this,
            text = self.text;
          if (text.length === 4) {
            self.pushState('p');
          } else {
            self.pushState('e');
          }
        },
        undefined,
        ['b'],
      ],
      [
        'c',
        /{{{?\//g,
        function () {
          var self = this,
            text = self.text;
          if (text.length === 4) {
            self.pushState('p');
          } else {
            self.pushState('e');
          }
        },
        undefined,
        ['b'],
      ],
      [
        'd',
        /{{\s*else\s*}}/g,
        function () {
          this.popState();
        },
        undefined,
        ['b'],
      ],
      [
        undefined,
        /{{![\s\S]*?}}/g,
        function () {
          this.popState();
        },
        undefined,
        ['b'],
      ],
      [
        'a',
        /{{%([\s\S]*?)%}}/g,
        function () {
          // return to content mode
          this.text = this.matches[1] || '';
          this.popState();
        },
        undefined,
        ['b'],
      ],
      [
        'e',
        /{{{?/g,
        function () {
          var self = this,
            text = self.text;
          if (text.length === 3) {
            self.pushState('p');
          } else {
            self.pushState('e');
          }
        },
        undefined,
        ['b'],
      ],
      [undefined, /\s+/g, undefined, undefined, ['c', 'd']],
      ['f', /,/g, undefined, undefined, ['c', 'd']],
      [
        'g',
        /}}}/g,
        function () {
          this.popState(2);
        },
        undefined,
        ['c'],
      ],
      [
        'g',
        /}}/g,
        function () {
          this.popState(2);
        },
        undefined,
        ['d'],
      ],
      ['h', /\(/g, undefined, undefined, ['c', 'd']],
      ['i', /\)/g, undefined, undefined, ['c', 'd']],
      ['j', /\|\|/g, undefined, undefined, ['c', 'd']],
      ['k', /&&/g, undefined, undefined, ['c', 'd']],
      ['l', /===/g, undefined, undefined, ['c', 'd']],
      ['m', /!==/g, undefined, undefined, ['c', 'd']],
      ['n', />=/g, undefined, undefined, ['c', 'd']],
      ['o', /<=/g, undefined, undefined, ['c', 'd']],
      ['p', />/g, undefined, undefined, ['c', 'd']],
      ['q', /</g, undefined, undefined, ['c', 'd']],
      ['r', /\+/g, undefined, undefined, ['c', 'd']],
      ['s', /-/g, undefined, undefined, ['c', 'd']],
      ['t', /\*/g, undefined, undefined, ['c', 'd']],
      ['u', /\//g, undefined, undefined, ['c', 'd']],
      ['v', /%/g, undefined, undefined, ['c', 'd']],
      ['w', /!/g, undefined, undefined, ['c', 'd']],
      [
        'x',
        /"(\[\s\S]|[^\"])*"/g,
        function () {
          this.text = this.text.slice(1, -1).replace(/\\"/g, '"');
        },
        undefined,
        ['c', 'd'],
      ],
      [
        'x',
        /'(\[\s\S]|[^\'])*'/g,
        function () {
          this.text = this.text.slice(1, -1).replace(/\\'/g, "'");
        },
        undefined,
        ['c', 'd'],
      ],
      ['y', /true/g, undefined, undefined, ['c', 'd']],
      ['y', /false/g, undefined, undefined, ['c', 'd']],
      ['z', /\d+(?:\.\d+)?(?:e-?\d+)?/gi, undefined, undefined, ['c', 'd']],
      ['aa', /=/g, undefined, undefined, ['c', 'd']],
      [
        'ab',
        /\.\./g,
        function () {
          // wait for '/'
          this.pushState('ws');
        },
        undefined,
        ['c', 'd'],
      ],
      [
        'ac',
        /\//g,
        function () {
          this.popState();
        },
        undefined,
        ['e'],
      ],
      ['ac', /\./g, undefined, undefined, ['c', 'd']],
      ['ad', /\[/g, undefined, undefined, ['c', 'd']],
      ['ae', /\]/g, undefined, undefined, ['c', 'd']],
      ['ab', /[a-zA-Z0-9_$]+/g, undefined, undefined, ['c', 'd']],
    ],
    isCompress: 1,
    defaultEnv: undefined,
  });
  lexer.stateMap = {
    I: 'I',
    et: 'a',
    t: 'b',
    p: 'c',
    e: 'd',
    ws: 'e',
  };
  function lex(input, options = {}) {
    lexer.options = options;
    lexer.resetInput(input);
    const { state } = options;

    if (state) {
      if (state.userData) {
        lexer.userData = state.userData;
      }

      if (state.stateStack) {
        lexer.stateStack = state.stateStack;
      }
    }

    while (lexer.lex().token !== Lexer.STATIC.EOF_TOKEN);

    return {
      state: {
        userData: lexer.userData,
        stateStack: lexer.stateStack,
      },
      tokens: lexer.tokens,
    };
  }
  var parser = {
    productions: [
      ['af', ['ag']],
      [
        'ag',
        ['ah', 'd', 'ah'],
        function () {
          return new this.yy.ProgramNode(
            this.lexer.lineNumber,
            this.$1,
            this.$3,
          );
        },
      ],
      [
        'ag',
        ['ah'],
        function () {
          return new this.yy.ProgramNode(this.lexer.lineNumber, this.$1);
        },
      ],
      [
        'ah',
        ['ai'],
        function () {
          return [this.$1];
        },
      ],
      [
        'ah',
        ['ah', 'ai'],
        function () {
          this.$1.push(this.$2);
        },
      ],
      [
        'ai',
        ['b', 'aj', 'g', 'ag', 'c', 'ak', 'g'],
        function () {
          return new this.yy.BlockStatement(
            this.lexer.lineNumber,
            this.$2,
            this.$4,
            this.$6,
            this.$1.length !== 4,
          );
        },
      ],
      [
        'ai',
        ['e', 'al', 'g'],
        function () {
          return new this.yy.ExpressionStatement(
            this.lexer.lineNumber,
            this.$2,
            this.$1.length !== 3,
          );
        },
      ],
      [
        'ai',
        ['a'],
        function () {
          return new this.yy.ContentStatement(this.lexer.lineNumber, this.$1);
        },
      ],
      [
        'aj',
        ['ak', 'h', 'am', 'f', 'an', 'i'],
        function () {
          return new this.yy.Function(
            this.lexer.lineNumber,
            this.$1,
            this.$3,
            this.$5,
          );
        },
      ],
      [
        'aj',
        ['ak', 'h', 'am', 'i'],
        function () {
          return new this.yy.Function(this.lexer.lineNumber, this.$1, this.$3);
        },
      ],
      [
        'aj',
        ['ak', 'h', 'an', 'i'],
        function () {
          return new this.yy.Function(
            this.lexer.lineNumber,
            this.$1,
            null,
            this.$3,
          );
        },
      ],
      [
        'aj',
        ['ak', 'h', 'i'],
        function () {
          return new this.yy.Function(this.lexer.lineNumber, this.$1);
        },
      ],
      [
        'am',
        ['am', 'f', 'ao'],
        function () {
          this.$1.push(this.$3);
        },
      ],
      [
        'am',
        ['ao'],
        function () {
          return [this.$1];
        },
      ],
      ['ao', ['al']],
      ['al', ['ap']],
      ['ap', ['aq']],
      [
        'ap',
        ['ap', 'j', 'aq'],
        function () {
          return new this.yy.ConditionalOrExpression(this.$1, this.$3);
        },
      ],
      ['aq', ['ar']],
      [
        'aq',
        ['aq', 'k', 'ar'],
        function () {
          return new this.yy.ConditionalAndExpression(this.$1, this.$3);
        },
      ],
      ['ar', ['as']],
      [
        'ar',
        ['ar', 'l', 'as'],
        function () {
          return new this.yy.EqualityExpression(this.$1, '===', this.$3);
        },
      ],
      [
        'ar',
        ['ar', 'm', 'as'],
        function () {
          return new this.yy.EqualityExpression(this.$1, '!==', this.$3);
        },
      ],
      ['as', ['at']],
      [
        'as',
        ['as', 'q', 'at'],
        function () {
          return new this.yy.RelationalExpression(this.$1, '<', this.$3);
        },
      ],
      [
        'as',
        ['as', 'p', 'at'],
        function () {
          return new this.yy.RelationalExpression(this.$1, '>', this.$3);
        },
      ],
      [
        'as',
        ['as', 'o', 'at'],
        function () {
          return new this.yy.RelationalExpression(this.$1, '<=', this.$3);
        },
      ],
      [
        'as',
        ['as', 'n', 'at'],
        function () {
          return new this.yy.RelationalExpression(this.$1, '>=', this.$3);
        },
      ],
      ['at', ['au']],
      [
        'at',
        ['at', 'r', 'au'],
        function () {
          return new this.yy.AdditiveExpression(this.$1, '+', this.$3);
        },
      ],
      [
        'at',
        ['at', 's', 'au'],
        function () {
          return new this.yy.AdditiveExpression(this.$1, '-', this.$3);
        },
      ],
      ['au', ['av']],
      [
        'au',
        ['au', 't', 'av'],
        function () {
          return new this.yy.MultiplicativeExpression(this.$1, '*', this.$3);
        },
      ],
      [
        'au',
        ['au', 'u', 'av'],
        function () {
          return new this.yy.MultiplicativeExpression(this.$1, '/', this.$3);
        },
      ],
      [
        'au',
        ['au', 'v', 'av'],
        function () {
          return new this.yy.MultiplicativeExpression(this.$1, '%', this.$3);
        },
      ],
      [
        'av',
        ['w', 'av'],
        function () {
          return new this.yy.UnaryExpression(this.$1, this.$2);
        },
      ],
      [
        'av',
        ['s', 'av'],
        function () {
          return new this.yy.UnaryExpression(this.$1, this.$2);
        },
      ],
      ['av', ['aw']],
      ['aw', ['aj']],
      [
        'aw',
        ['x'],
        function () {
          return new this.yy.String(this.lexer.lineNumber, this.$1);
        },
      ],
      [
        'aw',
        ['z'],
        function () {
          return new this.yy.Number(this.lexer.lineNumber, this.$1);
        },
      ],
      [
        'aw',
        ['y'],
        function () {
          return new this.yy.Boolean(this.lexer.lineNumber, this.$1);
        },
      ],
      ['aw', ['ak']],
      [
        'aw',
        ['h', 'al', 'i'],
        function () {
          return this.$2;
        },
      ],
      [
        'an',
        ['an', 'f', 'ax'],
        function () {
          var hash = this.$1,
            seg = this.$3;
          hash.value[seg[0]] = seg[1];
        },
      ],
      [
        'an',
        ['ax'],
        function () {
          var hash = new this.yy.Hash(this.lexer.lineNumber),
            $1 = this.$1;
          hash.value[$1[0]] = $1[1];
          return hash;
        },
      ],
      [
        'ax',
        ['ab', 'aa', 'al'],
        function () {
          return [this.$1, this.$3];
        },
      ],
      [
        'ak',
        ['ay'],
        function () {
          return new this.yy.Id(this.lexer.lineNumber, this.$1);
        },
      ],
      [
        'ay',
        ['ay', 'ac', 'ab'],
        function () {
          this.$1.push(this.$3);
        },
      ],
      [
        'ay',
        ['ay', 'ad', 'al', 'ae'],
        function () {
          this.$1.push(this.$3);
        },
      ],
      [
        'ay',
        ['ab'],
        function () {
          return [this.$1];
        },
      ],
    ],
    productionIndexMap: {
      symbol: 0,
      rhs: 1,
      action: 2,
      label: 3,
      predict: 4,
    },
    getProductionItemByType: function (p, itemType) {
      if (this.isCompress) {
        return p[this.productionIndexMap[itemType]];
      }

      return p[itemType];
    },
    getProductionSymbol: function (p) {
      return this.getProductionItemByType(p, 'symbol');
    },
    getProductionRhs: function (p) {
      return this.getProductionItemByType(p, 'rhs');
    },
    getProductionAction: function (p) {
      return this.getProductionItemByType(p, 'action');
    },
    getProductionPredict: function (p) {
      return this.getProductionItemByType(p, 'predict');
    },
    getProductionLabel: function (p) {
      return this.getProductionItemByType(p, 'label');
    },
    isCompress: 1,
  };
  parser.getProductionSymbol = parser.getProductionSymbol.bind(parser);
  parser.getProductionRhs = parser.getProductionRhs.bind(parser);
  parser.getProductionAction = parser.getProductionAction.bind(parser);
  parser.getProductionLabel = parser.getProductionLabel.bind(parser);
  parser.lexer = lexer;
  parser.lex = lex;
  parser.prioritySymbolMap = {};
  function peekStack(stack, n = 1) {
    return stack[stack.length - n];
  }
  var ActionTypeMap = ['accept', 'shift', 'reduce'];
  var GrammarConst = {
    SHIFT_TYPE: 1,
    REDUCE_TYPE: 2,
    ACCEPT_TYPE: 0,
    TYPE_INDEX: 0,
    VALUE_INDEX: 1,
  };
  parser.table = {
    gotos: {
      0: {
        ag: 4,
        ah: 5,
        ai: 6,
      },
      2: {
        aj: 8,
        ak: 9,
        ay: 10,
      },
      3: {
        aj: 17,
        ak: 18,
        al: 19,
        ap: 20,
        aq: 21,
        ar: 22,
        as: 23,
        at: 24,
        au: 25,
        av: 26,
        aw: 27,
        ay: 10,
      },
      5: {
        ai: 29,
      },
      11: {
        aj: 17,
        ak: 18,
        al: 34,
        ap: 20,
        aq: 21,
        ar: 22,
        as: 23,
        at: 24,
        au: 25,
        av: 26,
        aw: 27,
        ay: 10,
      },
      12: {
        aj: 17,
        ak: 18,
        av: 35,
        aw: 27,
        ay: 10,
      },
      13: {
        aj: 17,
        ak: 18,
        av: 36,
        aw: 27,
        ay: 10,
      },
      28: {
        ah: 51,
        ai: 6,
      },
      30: {
        ag: 52,
        ah: 5,
        ai: 6,
      },
      31: {
        aj: 17,
        ak: 18,
        al: 55,
        am: 56,
        an: 57,
        ao: 58,
        ap: 20,
        aq: 21,
        ar: 22,
        as: 23,
        at: 24,
        au: 25,
        av: 26,
        aw: 27,
        ax: 59,
        ay: 10,
      },
      33: {
        aj: 17,
        ak: 18,
        al: 61,
        ap: 20,
        aq: 21,
        ar: 22,
        as: 23,
        at: 24,
        au: 25,
        av: 26,
        aw: 27,
        ay: 10,
      },
      38: {
        aj: 17,
        ak: 18,
        aq: 63,
        ar: 22,
        as: 23,
        at: 24,
        au: 25,
        av: 26,
        aw: 27,
        ay: 10,
      },
      39: {
        aj: 17,
        ak: 18,
        ar: 64,
        as: 23,
        at: 24,
        au: 25,
        av: 26,
        aw: 27,
        ay: 10,
      },
      40: {
        aj: 17,
        ak: 18,
        as: 65,
        at: 24,
        au: 25,
        av: 26,
        aw: 27,
        ay: 10,
      },
      41: {
        aj: 17,
        ak: 18,
        as: 66,
        at: 24,
        au: 25,
        av: 26,
        aw: 27,
        ay: 10,
      },
      42: {
        aj: 17,
        ak: 18,
        at: 67,
        au: 25,
        av: 26,
        aw: 27,
        ay: 10,
      },
      43: {
        aj: 17,
        ak: 18,
        at: 68,
        au: 25,
        av: 26,
        aw: 27,
        ay: 10,
      },
      44: {
        aj: 17,
        ak: 18,
        at: 69,
        au: 25,
        av: 26,
        aw: 27,
        ay: 10,
      },
      45: {
        aj: 17,
        ak: 18,
        at: 70,
        au: 25,
        av: 26,
        aw: 27,
        ay: 10,
      },
      46: {
        aj: 17,
        ak: 18,
        au: 71,
        av: 26,
        aw: 27,
        ay: 10,
      },
      47: {
        aj: 17,
        ak: 18,
        au: 72,
        av: 26,
        aw: 27,
        ay: 10,
      },
      48: {
        aj: 17,
        ak: 18,
        av: 73,
        aw: 27,
        ay: 10,
      },
      49: {
        aj: 17,
        ak: 18,
        av: 74,
        aw: 27,
        ay: 10,
      },
      50: {
        aj: 17,
        ak: 18,
        av: 75,
        aw: 27,
        ay: 10,
      },
      51: {
        ai: 29,
      },
      76: {
        ak: 83,
        ay: 10,
      },
      77: {
        aj: 17,
        ak: 18,
        al: 84,
        ap: 20,
        aq: 21,
        ar: 22,
        as: 23,
        at: 24,
        au: 25,
        av: 26,
        aw: 27,
        ay: 10,
      },
      78: {
        aj: 17,
        ak: 18,
        al: 55,
        an: 85,
        ao: 86,
        ap: 20,
        aq: 21,
        ar: 22,
        as: 23,
        at: 24,
        au: 25,
        av: 26,
        aw: 27,
        ax: 59,
        ay: 10,
      },
      80: {
        ax: 88,
      },
    },
    action: {
      0: {
        a: [1, 1],
        b: [1, 2],
        e: [1, 3],
      },
      1: {
        az: [2, 7],
        d: [2, 7],
        b: [2, 7],
        e: [2, 7],
        a: [2, 7],
        c: [2, 7],
      },
      2: {
        ab: [1, 7],
      },
      3: {
        h: [1, 11],
        s: [1, 12],
        w: [1, 13],
        x: [1, 14],
        y: [1, 15],
        z: [1, 16],
        ab: [1, 7],
      },
      4: {
        az: [0],
      },
      5: {
        az: [2, 2],
        c: [2, 2],
        a: [1, 1],
        b: [1, 2],
        d: [1, 28],
        e: [1, 3],
      },
      6: {
        az: [2, 3],
        d: [2, 3],
        b: [2, 3],
        e: [2, 3],
        a: [2, 3],
        c: [2, 3],
      },
      7: {
        h: [2, 50],
        ad: [2, 50],
        ac: [2, 50],
        g: [2, 50],
        s: [2, 50],
        r: [2, 50],
        u: [2, 50],
        v: [2, 50],
        t: [2, 50],
        k: [2, 50],
        j: [2, 50],
        l: [2, 50],
        m: [2, 50],
        n: [2, 50],
        p: [2, 50],
        o: [2, 50],
        q: [2, 50],
        i: [2, 50],
        ae: [2, 50],
        f: [2, 50],
      },
      8: {
        g: [1, 30],
      },
      9: {
        h: [1, 31],
      },
      10: {
        h: [2, 47],
        g: [2, 47],
        s: [2, 47],
        r: [2, 47],
        u: [2, 47],
        v: [2, 47],
        t: [2, 47],
        k: [2, 47],
        j: [2, 47],
        l: [2, 47],
        m: [2, 47],
        n: [2, 47],
        p: [2, 47],
        o: [2, 47],
        q: [2, 47],
        i: [2, 47],
        f: [2, 47],
        ae: [2, 47],
        ac: [1, 32],
        ad: [1, 33],
      },
      11: {
        h: [1, 11],
        s: [1, 12],
        w: [1, 13],
        x: [1, 14],
        y: [1, 15],
        z: [1, 16],
        ab: [1, 7],
      },
      12: {
        h: [1, 11],
        s: [1, 12],
        w: [1, 13],
        x: [1, 14],
        y: [1, 15],
        z: [1, 16],
        ab: [1, 7],
      },
      13: {
        h: [1, 11],
        s: [1, 12],
        w: [1, 13],
        x: [1, 14],
        y: [1, 15],
        z: [1, 16],
        ab: [1, 7],
      },
      14: {
        g: [2, 39],
        s: [2, 39],
        r: [2, 39],
        u: [2, 39],
        v: [2, 39],
        t: [2, 39],
        k: [2, 39],
        j: [2, 39],
        l: [2, 39],
        m: [2, 39],
        n: [2, 39],
        p: [2, 39],
        o: [2, 39],
        q: [2, 39],
        i: [2, 39],
        f: [2, 39],
        ae: [2, 39],
      },
      15: {
        g: [2, 41],
        s: [2, 41],
        r: [2, 41],
        u: [2, 41],
        v: [2, 41],
        t: [2, 41],
        k: [2, 41],
        j: [2, 41],
        l: [2, 41],
        m: [2, 41],
        n: [2, 41],
        p: [2, 41],
        o: [2, 41],
        q: [2, 41],
        i: [2, 41],
        f: [2, 41],
        ae: [2, 41],
      },
      16: {
        g: [2, 40],
        s: [2, 40],
        r: [2, 40],
        u: [2, 40],
        v: [2, 40],
        t: [2, 40],
        k: [2, 40],
        j: [2, 40],
        l: [2, 40],
        m: [2, 40],
        n: [2, 40],
        p: [2, 40],
        o: [2, 40],
        q: [2, 40],
        i: [2, 40],
        f: [2, 40],
        ae: [2, 40],
      },
      17: {
        g: [2, 38],
        s: [2, 38],
        r: [2, 38],
        u: [2, 38],
        v: [2, 38],
        t: [2, 38],
        k: [2, 38],
        j: [2, 38],
        l: [2, 38],
        m: [2, 38],
        n: [2, 38],
        p: [2, 38],
        o: [2, 38],
        q: [2, 38],
        i: [2, 38],
        f: [2, 38],
        ae: [2, 38],
      },
      18: {
        g: [2, 42],
        s: [2, 42],
        r: [2, 42],
        u: [2, 42],
        v: [2, 42],
        t: [2, 42],
        k: [2, 42],
        j: [2, 42],
        l: [2, 42],
        m: [2, 42],
        n: [2, 42],
        p: [2, 42],
        o: [2, 42],
        q: [2, 42],
        i: [2, 42],
        f: [2, 42],
        ae: [2, 42],
        h: [1, 31],
      },
      19: {
        g: [1, 37],
      },
      20: {
        g: [2, 15],
        i: [2, 15],
        f: [2, 15],
        ae: [2, 15],
        j: [1, 38],
      },
      21: {
        g: [2, 16],
        j: [2, 16],
        i: [2, 16],
        f: [2, 16],
        ae: [2, 16],
        k: [1, 39],
      },
      22: {
        g: [2, 18],
        k: [2, 18],
        j: [2, 18],
        i: [2, 18],
        f: [2, 18],
        ae: [2, 18],
        l: [1, 40],
        m: [1, 41],
      },
      23: {
        g: [2, 20],
        k: [2, 20],
        j: [2, 20],
        l: [2, 20],
        m: [2, 20],
        i: [2, 20],
        f: [2, 20],
        ae: [2, 20],
        n: [1, 42],
        o: [1, 43],
        p: [1, 44],
        q: [1, 45],
      },
      24: {
        g: [2, 23],
        k: [2, 23],
        j: [2, 23],
        l: [2, 23],
        m: [2, 23],
        n: [2, 23],
        p: [2, 23],
        o: [2, 23],
        q: [2, 23],
        i: [2, 23],
        f: [2, 23],
        ae: [2, 23],
        r: [1, 46],
        s: [1, 47],
      },
      25: {
        g: [2, 28],
        s: [2, 28],
        r: [2, 28],
        k: [2, 28],
        j: [2, 28],
        l: [2, 28],
        m: [2, 28],
        n: [2, 28],
        p: [2, 28],
        o: [2, 28],
        q: [2, 28],
        i: [2, 28],
        f: [2, 28],
        ae: [2, 28],
        t: [1, 48],
        u: [1, 49],
        v: [1, 50],
      },
      26: {
        g: [2, 31],
        s: [2, 31],
        r: [2, 31],
        u: [2, 31],
        v: [2, 31],
        t: [2, 31],
        k: [2, 31],
        j: [2, 31],
        l: [2, 31],
        m: [2, 31],
        n: [2, 31],
        p: [2, 31],
        o: [2, 31],
        q: [2, 31],
        i: [2, 31],
        f: [2, 31],
        ae: [2, 31],
      },
      27: {
        g: [2, 37],
        s: [2, 37],
        r: [2, 37],
        u: [2, 37],
        v: [2, 37],
        t: [2, 37],
        k: [2, 37],
        j: [2, 37],
        l: [2, 37],
        m: [2, 37],
        n: [2, 37],
        p: [2, 37],
        o: [2, 37],
        q: [2, 37],
        i: [2, 37],
        f: [2, 37],
        ae: [2, 37],
      },
      28: {
        a: [1, 1],
        b: [1, 2],
        e: [1, 3],
      },
      29: {
        az: [2, 4],
        d: [2, 4],
        b: [2, 4],
        e: [2, 4],
        a: [2, 4],
        c: [2, 4],
      },
      30: {
        a: [1, 1],
        b: [1, 2],
        e: [1, 3],
      },
      31: {
        h: [1, 11],
        i: [1, 53],
        s: [1, 12],
        w: [1, 13],
        x: [1, 14],
        y: [1, 15],
        z: [1, 16],
        ab: [1, 54],
      },
      32: {
        ab: [1, 60],
      },
      33: {
        h: [1, 11],
        s: [1, 12],
        w: [1, 13],
        x: [1, 14],
        y: [1, 15],
        z: [1, 16],
        ab: [1, 7],
      },
      34: {
        i: [1, 62],
      },
      35: {
        g: [2, 36],
        s: [2, 36],
        r: [2, 36],
        u: [2, 36],
        v: [2, 36],
        t: [2, 36],
        k: [2, 36],
        j: [2, 36],
        l: [2, 36],
        m: [2, 36],
        n: [2, 36],
        p: [2, 36],
        o: [2, 36],
        q: [2, 36],
        i: [2, 36],
        f: [2, 36],
        ae: [2, 36],
      },
      36: {
        g: [2, 35],
        s: [2, 35],
        r: [2, 35],
        u: [2, 35],
        v: [2, 35],
        t: [2, 35],
        k: [2, 35],
        j: [2, 35],
        l: [2, 35],
        m: [2, 35],
        n: [2, 35],
        p: [2, 35],
        o: [2, 35],
        q: [2, 35],
        i: [2, 35],
        f: [2, 35],
        ae: [2, 35],
      },
      37: {
        az: [2, 6],
        d: [2, 6],
        b: [2, 6],
        e: [2, 6],
        a: [2, 6],
        c: [2, 6],
      },
      38: {
        h: [1, 11],
        s: [1, 12],
        w: [1, 13],
        x: [1, 14],
        y: [1, 15],
        z: [1, 16],
        ab: [1, 7],
      },
      39: {
        h: [1, 11],
        s: [1, 12],
        w: [1, 13],
        x: [1, 14],
        y: [1, 15],
        z: [1, 16],
        ab: [1, 7],
      },
      40: {
        h: [1, 11],
        s: [1, 12],
        w: [1, 13],
        x: [1, 14],
        y: [1, 15],
        z: [1, 16],
        ab: [1, 7],
      },
      41: {
        h: [1, 11],
        s: [1, 12],
        w: [1, 13],
        x: [1, 14],
        y: [1, 15],
        z: [1, 16],
        ab: [1, 7],
      },
      42: {
        h: [1, 11],
        s: [1, 12],
        w: [1, 13],
        x: [1, 14],
        y: [1, 15],
        z: [1, 16],
        ab: [1, 7],
      },
      43: {
        h: [1, 11],
        s: [1, 12],
        w: [1, 13],
        x: [1, 14],
        y: [1, 15],
        z: [1, 16],
        ab: [1, 7],
      },
      44: {
        h: [1, 11],
        s: [1, 12],
        w: [1, 13],
        x: [1, 14],
        y: [1, 15],
        z: [1, 16],
        ab: [1, 7],
      },
      45: {
        h: [1, 11],
        s: [1, 12],
        w: [1, 13],
        x: [1, 14],
        y: [1, 15],
        z: [1, 16],
        ab: [1, 7],
      },
      46: {
        h: [1, 11],
        s: [1, 12],
        w: [1, 13],
        x: [1, 14],
        y: [1, 15],
        z: [1, 16],
        ab: [1, 7],
      },
      47: {
        h: [1, 11],
        s: [1, 12],
        w: [1, 13],
        x: [1, 14],
        y: [1, 15],
        z: [1, 16],
        ab: [1, 7],
      },
      48: {
        h: [1, 11],
        s: [1, 12],
        w: [1, 13],
        x: [1, 14],
        y: [1, 15],
        z: [1, 16],
        ab: [1, 7],
      },
      49: {
        h: [1, 11],
        s: [1, 12],
        w: [1, 13],
        x: [1, 14],
        y: [1, 15],
        z: [1, 16],
        ab: [1, 7],
      },
      50: {
        h: [1, 11],
        s: [1, 12],
        w: [1, 13],
        x: [1, 14],
        y: [1, 15],
        z: [1, 16],
        ab: [1, 7],
      },
      51: {
        az: [2, 1],
        c: [2, 1],
        a: [1, 1],
        b: [1, 2],
        e: [1, 3],
      },
      52: {
        c: [1, 76],
      },
      53: {
        g: [2, 11],
        s: [2, 11],
        r: [2, 11],
        u: [2, 11],
        v: [2, 11],
        t: [2, 11],
        k: [2, 11],
        j: [2, 11],
        l: [2, 11],
        m: [2, 11],
        n: [2, 11],
        p: [2, 11],
        o: [2, 11],
        q: [2, 11],
        i: [2, 11],
        f: [2, 11],
        ae: [2, 11],
      },
      54: {
        f: [2, 50],
        s: [2, 50],
        h: [2, 50],
        ad: [2, 50],
        ac: [2, 50],
        r: [2, 50],
        u: [2, 50],
        v: [2, 50],
        t: [2, 50],
        k: [2, 50],
        j: [2, 50],
        l: [2, 50],
        m: [2, 50],
        i: [2, 50],
        n: [2, 50],
        p: [2, 50],
        o: [2, 50],
        q: [2, 50],
        aa: [1, 77],
      },
      55: {
        f: [2, 14],
        i: [2, 14],
      },
      56: {
        f: [1, 78],
        i: [1, 79],
      },
      57: {
        f: [1, 80],
        i: [1, 81],
      },
      58: {
        f: [2, 13],
        i: [2, 13],
      },
      59: {
        i: [2, 45],
        f: [2, 45],
      },
      60: {
        h: [2, 48],
        ad: [2, 48],
        ac: [2, 48],
        g: [2, 48],
        s: [2, 48],
        r: [2, 48],
        u: [2, 48],
        v: [2, 48],
        t: [2, 48],
        k: [2, 48],
        j: [2, 48],
        l: [2, 48],
        m: [2, 48],
        n: [2, 48],
        p: [2, 48],
        o: [2, 48],
        q: [2, 48],
        i: [2, 48],
        f: [2, 48],
        ae: [2, 48],
      },
      61: {
        ae: [1, 82],
      },
      62: {
        g: [2, 43],
        s: [2, 43],
        r: [2, 43],
        u: [2, 43],
        v: [2, 43],
        t: [2, 43],
        k: [2, 43],
        j: [2, 43],
        l: [2, 43],
        m: [2, 43],
        n: [2, 43],
        p: [2, 43],
        o: [2, 43],
        q: [2, 43],
        i: [2, 43],
        f: [2, 43],
        ae: [2, 43],
      },
      63: {
        g: [2, 17],
        j: [2, 17],
        i: [2, 17],
        f: [2, 17],
        ae: [2, 17],
        k: [1, 39],
      },
      64: {
        g: [2, 19],
        k: [2, 19],
        j: [2, 19],
        i: [2, 19],
        f: [2, 19],
        ae: [2, 19],
        l: [1, 40],
        m: [1, 41],
      },
      65: {
        g: [2, 21],
        k: [2, 21],
        j: [2, 21],
        l: [2, 21],
        m: [2, 21],
        i: [2, 21],
        f: [2, 21],
        ae: [2, 21],
        n: [1, 42],
        o: [1, 43],
        p: [1, 44],
        q: [1, 45],
      },
      66: {
        g: [2, 22],
        k: [2, 22],
        j: [2, 22],
        l: [2, 22],
        m: [2, 22],
        i: [2, 22],
        f: [2, 22],
        ae: [2, 22],
        n: [1, 42],
        o: [1, 43],
        p: [1, 44],
        q: [1, 45],
      },
      67: {
        g: [2, 27],
        k: [2, 27],
        j: [2, 27],
        l: [2, 27],
        m: [2, 27],
        n: [2, 27],
        p: [2, 27],
        o: [2, 27],
        q: [2, 27],
        i: [2, 27],
        f: [2, 27],
        ae: [2, 27],
        r: [1, 46],
        s: [1, 47],
      },
      68: {
        g: [2, 26],
        k: [2, 26],
        j: [2, 26],
        l: [2, 26],
        m: [2, 26],
        n: [2, 26],
        p: [2, 26],
        o: [2, 26],
        q: [2, 26],
        i: [2, 26],
        f: [2, 26],
        ae: [2, 26],
        r: [1, 46],
        s: [1, 47],
      },
      69: {
        g: [2, 25],
        k: [2, 25],
        j: [2, 25],
        l: [2, 25],
        m: [2, 25],
        n: [2, 25],
        p: [2, 25],
        o: [2, 25],
        q: [2, 25],
        i: [2, 25],
        f: [2, 25],
        ae: [2, 25],
        r: [1, 46],
        s: [1, 47],
      },
      70: {
        g: [2, 24],
        k: [2, 24],
        j: [2, 24],
        l: [2, 24],
        m: [2, 24],
        n: [2, 24],
        p: [2, 24],
        o: [2, 24],
        q: [2, 24],
        i: [2, 24],
        f: [2, 24],
        ae: [2, 24],
        r: [1, 46],
        s: [1, 47],
      },
      71: {
        g: [2, 29],
        s: [2, 29],
        r: [2, 29],
        k: [2, 29],
        j: [2, 29],
        l: [2, 29],
        m: [2, 29],
        n: [2, 29],
        p: [2, 29],
        o: [2, 29],
        q: [2, 29],
        i: [2, 29],
        f: [2, 29],
        ae: [2, 29],
        t: [1, 48],
        u: [1, 49],
        v: [1, 50],
      },
      72: {
        g: [2, 30],
        s: [2, 30],
        r: [2, 30],
        k: [2, 30],
        j: [2, 30],
        l: [2, 30],
        m: [2, 30],
        n: [2, 30],
        p: [2, 30],
        o: [2, 30],
        q: [2, 30],
        i: [2, 30],
        f: [2, 30],
        ae: [2, 30],
        t: [1, 48],
        u: [1, 49],
        v: [1, 50],
      },
      73: {
        g: [2, 32],
        s: [2, 32],
        r: [2, 32],
        u: [2, 32],
        v: [2, 32],
        t: [2, 32],
        k: [2, 32],
        j: [2, 32],
        l: [2, 32],
        m: [2, 32],
        n: [2, 32],
        p: [2, 32],
        o: [2, 32],
        q: [2, 32],
        i: [2, 32],
        f: [2, 32],
        ae: [2, 32],
      },
      74: {
        g: [2, 33],
        s: [2, 33],
        r: [2, 33],
        u: [2, 33],
        v: [2, 33],
        t: [2, 33],
        k: [2, 33],
        j: [2, 33],
        l: [2, 33],
        m: [2, 33],
        n: [2, 33],
        p: [2, 33],
        o: [2, 33],
        q: [2, 33],
        i: [2, 33],
        f: [2, 33],
        ae: [2, 33],
      },
      75: {
        g: [2, 34],
        s: [2, 34],
        r: [2, 34],
        u: [2, 34],
        v: [2, 34],
        t: [2, 34],
        k: [2, 34],
        j: [2, 34],
        l: [2, 34],
        m: [2, 34],
        n: [2, 34],
        p: [2, 34],
        o: [2, 34],
        q: [2, 34],
        i: [2, 34],
        f: [2, 34],
        ae: [2, 34],
      },
      76: {
        ab: [1, 7],
      },
      77: {
        h: [1, 11],
        s: [1, 12],
        w: [1, 13],
        x: [1, 14],
        y: [1, 15],
        z: [1, 16],
        ab: [1, 7],
      },
      78: {
        h: [1, 11],
        s: [1, 12],
        w: [1, 13],
        x: [1, 14],
        y: [1, 15],
        z: [1, 16],
        ab: [1, 54],
      },
      79: {
        g: [2, 9],
        s: [2, 9],
        r: [2, 9],
        u: [2, 9],
        v: [2, 9],
        t: [2, 9],
        k: [2, 9],
        j: [2, 9],
        l: [2, 9],
        m: [2, 9],
        n: [2, 9],
        p: [2, 9],
        o: [2, 9],
        q: [2, 9],
        i: [2, 9],
        f: [2, 9],
        ae: [2, 9],
      },
      80: {
        ab: [1, 87],
      },
      81: {
        g: [2, 10],
        s: [2, 10],
        r: [2, 10],
        u: [2, 10],
        v: [2, 10],
        t: [2, 10],
        k: [2, 10],
        j: [2, 10],
        l: [2, 10],
        m: [2, 10],
        n: [2, 10],
        p: [2, 10],
        o: [2, 10],
        q: [2, 10],
        i: [2, 10],
        f: [2, 10],
        ae: [2, 10],
      },
      82: {
        h: [2, 49],
        ad: [2, 49],
        ac: [2, 49],
        g: [2, 49],
        s: [2, 49],
        r: [2, 49],
        u: [2, 49],
        v: [2, 49],
        t: [2, 49],
        k: [2, 49],
        j: [2, 49],
        l: [2, 49],
        m: [2, 49],
        n: [2, 49],
        p: [2, 49],
        o: [2, 49],
        q: [2, 49],
        i: [2, 49],
        f: [2, 49],
        ae: [2, 49],
      },
      83: {
        g: [1, 89],
      },
      84: {
        i: [2, 46],
        f: [2, 46],
      },
      85: {
        f: [1, 80],
        i: [1, 90],
      },
      86: {
        f: [2, 12],
        i: [2, 12],
      },
      87: {
        aa: [1, 77],
      },
      88: {
        i: [2, 44],
        f: [2, 44],
      },
      89: {
        az: [2, 5],
        d: [2, 5],
        b: [2, 5],
        e: [2, 5],
        a: [2, 5],
        c: [2, 5],
      },
      90: {
        g: [2, 8],
        s: [2, 8],
        r: [2, 8],
        u: [2, 8],
        v: [2, 8],
        t: [2, 8],
        k: [2, 8],
        j: [2, 8],
        l: [2, 8],
        m: [2, 8],
        n: [2, 8],
        p: [2, 8],
        o: [2, 8],
        q: [2, 8],
        i: [2, 8],
        f: [2, 8],
        ae: [2, 8],
      },
    },
  };
  parser.parse = function parse(input, options) {
    options = options || {};
    var { filename } = options;
    var state, token, ret, action, $$;
    var {
      getProductionSymbol,
      getProductionRhs,
      getProductionAction,
      productions,
    } = parser;
    var table = parser.table;
    var { gotos, action: tableAction } = table; // for debug info

    var prefix = filename ? 'in file: ' + filename + ' ' : '';
    var valueStack = [];
    var stateStack = [0];
    var symbolStack = [];
    lexer.resetInput(input);

    while (1) {
      // retrieve state number from top of stack
      state = peekStack(stateStack);

      if (!token) {
        token = lexer.lex();
      }

      if (token) {
        // read action for current state and first input
        action = tableAction[state] && tableAction[state][token.t];
      } else {
        action = null;
      }

      if (!action) {
        var expectedInfo = [];
        var expected = {};

        if (tableAction[state]) {
          const map = tableAction[state];

          for (const symbolForState of Object.keys(map)) {
            const v = map[symbolForState];
            action = v[GrammarConst.TYPE_INDEX];
            const actionStr = ActionTypeMap[action];
            const arr = (expected[actionStr] = expected[actionStr] || []);
            const s = lexer.mapReverseSymbol(symbolForState);
            arr.push(s);
            expectedInfo.push(actionStr + ':' + s);
          }
        }

        const error =
          prefix +
          'syntax error at line ' +
          lexer.lineNumber +
          ':\n' +
          lexer.showDebugInfo() +
          '\n' +
          'expect ' +
          expectedInfo.join(', ');
        throw new Error(error);
      }

      switch (action[GrammarConst.TYPE_INDEX]) {
        case GrammarConst.SHIFT_TYPE:
          symbolStack.push(token.t);
          valueStack.push(lexer.text); // push state

          stateStack.push(action[GrammarConst.VALUE_INDEX]); // allow to read more

          token = null;
          break;

        case GrammarConst.REDUCE_TYPE:
          var production = productions[action[GrammarConst.VALUE_INDEX]];
          var reducedSymbol = getProductionSymbol(production);
          var reducedAction = getProductionAction(production);
          var reducedRhs = getProductionRhs(production);
          var len = reducedRhs.length;
          $$ = peekStack(valueStack, len); // default to $$ = $1

          ret = undefined;
          const p = parser;
          p.$$ = $$;

          for (var i = 0; i < len; i++) {
            p['$' + (len - i)] = peekStack(valueStack, i + 1);
          }

          if (reducedAction) {
            ret = reducedAction.call(p);
          }

          if (ret !== undefined) {
            $$ = ret;
          } else {
            $$ = p.$$;
          }

          var reverseIndex = len * -1;
          stateStack.splice(reverseIndex, len);
          valueStack.splice(reverseIndex, len);
          symbolStack.splice(reverseIndex, len);
          symbolStack.push(reducedSymbol);
          valueStack.push($$);
          var newState = gotos[peekStack(stateStack)][reducedSymbol];
          stateStack.push(newState);
          break;

        case GrammarConst.ACCEPT_TYPE:
          return $$;
      }
    }
  };
  var productionRuleIndexMap = {
    0: 1,
    1: 1,
    2: 2,
    3: 3,
    4: 4,
    5: 5,
    6: 6,
    7: 7,
    8: 8,
    9: 9,
    10: 10,
    11: 11,
    12: 12,
    13: 13,
    14: 14,
    15: 15,
    16: 16,
    17: 17,
    18: 18,
    19: 19,
    20: 20,
    21: 21,
    22: 22,
    23: 23,
    24: 24,
    25: 25,
    26: 26,
    27: 27,
    28: 28,
    29: 29,
    30: 30,
    31: 31,
    32: 32,
    33: 33,
    34: 34,
    35: 35,
    36: 36,
    37: 37,
    38: 38,
    39: 39,
    40: 40,
    41: 41,
    42: 42,
    43: 43,
    44: 44,
    45: 45,
    46: 46,
    47: 47,
    48: 48,
    49: 49,
    50: 50,
  };
  lexer.symbolMap = {
    CONTENT: 'a',
    OPEN_BLOCK: 'b',
    OPEN_CLOSE_BLOCK: 'c',
    INVERSE: 'd',
    OPEN_TPL: 'e',
    COMMA: 'f',
    CLOSE: 'g',
    LPAREN: 'h',
    RPAREN: 'i',
    OR: 'j',
    AND: 'k',
    LOGIC_EQUALS: 'l',
    LOGIC_NOT_EQUALS: 'm',
    GE: 'n',
    LE: 'o',
    GT: 'p',
    LT: 'q',
    PLUS: 'r',
    MINUS: 's',
    MULTIPLY: 't',
    DIVIDE: 'u',
    MODULUS: 'v',
    NOT: 'w',
    STRING: 'x',
    BOOLEAN: 'y',
    NUMBER: 'z',
    EQUALS: 'aa',
    ID: 'ab',
    SEP: 'ac',
    REF_START: 'ad',
    REF_END: 'ae',
    $START: 'af',
    program: 'ag',
    statements: 'ah',
    statement: 'ai',
    function: 'aj',
    id: 'ak',
    expression: 'al',
    params: 'am',
    hash: 'an',
    param: 'ao',
    conditionalOrExpression: 'ap',
    conditionalAndExpression: 'aq',
    equalityExpression: 'ar',
    relationalExpression: 'as',
    additiveExpression: 'at',
    multiplicativeExpression: 'au',
    unaryExpression: 'av',
    primaryExpression: 'aw',
    hashSegment: 'ax',
    idSegments: 'ay',
    $EOF: 'az',
  };
  return parser;
})();

if (typeof module !== 'undefined') {
  module.exports = $parser;
}
